//-----------------------------------------------------------------------------
//  Copyright (C) 2011-2026, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  this license grant, this restriction and the following disclaimer, must be
//  included in all copies of the Software, in whole or in part, and all
//  derivative works of the Software, unless such copies or derivative works are
//  solely in the form of machine-executable object code generated by a source
//  language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
//  ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

#include "gbdb.h"
#include <algorithm>
#include <cctype>
#include <charconv>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iterator>
#include <limits>
#include <optional>
#include <sstream>

#if defined(GB_YADRO_ENABLE_AXE_JSON)
#   if __has_include(<axe.h>)
#       include <axe.h>
#       define GB_YADRO_GBDB_JSON_HAS_AXE 1
#   else
#       error "GB_YADRO_ENABLE_AXE_JSON requires AXE include directory with <axe.h>"
#   endif
#else
#   define GB_YADRO_GBDB_JSON_HAS_AXE 0
#endif

namespace gb::yadro::container
{
    inline constexpr bool gbdb_json_axe_enabled = GB_YADRO_GBDB_JSON_HAS_AXE != 0;

    struct json_parse_error : std::runtime_error
    {
        std::size_t offset = 0;
        std::uint32_t line = 0;
        std::uint32_t column = 0;

        json_parse_error(std::string message, std::size_t offset, std::uint32_t line, std::uint32_t column)
            : std::runtime_error(std::move(message)), offset(offset), line(line), column(column)
        {}
    };

    struct json_read_options
    {
        bool reject_duplicate_keys = true;
    };

    struct json_write_options
    {
        bool pretty = true;
        std::uint32_t indent = 2;
        bool sort_keys = false;
        bool ascii_only = false;
    };

    class json_db_builder
    {
    public:
        using db_type = json_db;
        using string_type = db_type::string_type;
        using string_view = db_type::string_view;

        json_db_builder() = default;
        explicit json_db_builder(json_read_options options)
            : _read_options(options)
        {}

        void begin_object()
        {
            ensure_not_array("JSON objects inside arrays are not supported by json_db_builder");

            if (_pending_key) {
                auto path = path_with_pending_key();
                reject_duplicate(path);
                _db.set(std::span<const string_view>{ path.data(), path.size() }, nullptr);
                _path.push_back(std::move(*_pending_key));
                _pending_key.reset();
                _objects.push_back(object_state{ .pushed_path = true });
                return;
            }

            if (!_objects.empty())
                throw std::logic_error("JSON object member is missing a key");

            _objects.push_back(object_state{});
        }

        void end_object()
        {
            if (_objects.empty())
                throw std::logic_error("JSON object end without matching begin");
            if (_pending_key)
                throw std::logic_error("JSON object key is missing a value");

            if (_objects.back().pushed_path)
                _path.pop_back();
            _objects.pop_back();
        }

        void key(string_view value)
        {
            ensure_not_array("JSON object keys are not valid inside arrays");
            if (_objects.empty())
                throw std::logic_error("JSON object key outside object");
            if (_pending_key)
                throw std::logic_error("JSON object key is missing a value");

            _pending_key = string_type{ value };
        }

        void null_value()
        {
            set_value(nullptr);
        }

        void bool_value(bool value)
        {
            if (_array)
                throw std::logic_error("Boolean arrays are not supported by the current json_db value model");
            set_value(value);
        }

        void int_value(std::int64_t value)
        {
            if (_array) {
                append_int(value);
                return;
            }
            set_value(value);
        }

        void uint_value(std::uint64_t value)
        {
            if (_array) {
                append_uint(value);
                return;
            }
            set_value(value);
        }

        void double_value(double value)
        {
            if (_array) {
                append_double(value);
                return;
            }
            set_value(value);
        }

        void string_value(string_view value)
        {
            if (_array) {
                append_string(value);
                return;
            }
            set_value(value);
        }

        void begin_array()
        {
            ensure_not_array("Nested arrays are not supported by the current json_db value model");
            if (!_pending_key)
                throw std::logic_error("JSON array member is missing a key");

            _array = array_state{};
            _array->path_storage = _path;
            _array->path_storage.push_back(std::move(*_pending_key));
            _pending_key.reset();
        }

        void end_array()
        {
            if (!_array)
                throw std::logic_error("JSON array end without matching begin");

            auto path = views(_array->path_storage);
            reject_duplicate(path);

            switch (_array->kind) {
            case array_kind::none:
            case array_kind::strings: {
                auto values = views(_array->strings);
                _db.set_string_array(
                    std::span<const string_view>{ path.data(), path.size() },
                    std::span<const string_view>{ values.data(), values.size() });
                break;
            }
            case array_kind::signed_int:
                _db.set_array(std::span<const string_view>{ path.data(), path.size() }, std::span<const std::int64_t>{ _array->ints.data(), _array->ints.size() });
                break;
            case array_kind::unsigned_int:
                _db.set_array(std::span<const string_view>{ path.data(), path.size() }, std::span<const std::uint64_t>{ _array->uints.data(), _array->uints.size() });
                break;
            case array_kind::floating:
                _db.set_array(std::span<const string_view>{ path.data(), path.size() }, std::span<const double>{ _array->doubles.data(), _array->doubles.size() });
                break;
            }

            _array.reset();
        }

        [[nodiscard]] db_type finish() &&
        {
            if (!_objects.empty())
                throw std::logic_error("JSON object is not closed");
            if (_array)
                throw std::logic_error("JSON array is not closed");
            if (_pending_key)
                throw std::logic_error("JSON object key is missing a value");
            return std::move(_db);
        }

    private:
        struct object_state
        {
            bool pushed_path = false;
        };

        enum class array_kind
        {
            none,
            signed_int,
            unsigned_int,
            floating,
            strings
        };

        struct array_state
        {
            std::vector<string_type> path_storage;
            array_kind kind = array_kind::none;
            std::vector<std::int64_t> ints;
            std::vector<std::uint64_t> uints;
            std::vector<double> doubles;
            std::vector<string_type> strings;
        };

        [[nodiscard]] std::vector<string_view> current_path() const
        {
            return views(_path);
        }

        [[nodiscard]] std::vector<string_view> path_with_pending_key() const
        {
            auto path = current_path();
            path.push_back(*_pending_key);
            return path;
        }

        [[nodiscard]] static std::vector<string_view> views(const std::vector<string_type>& values)
        {
            std::vector<string_view> result;
            result.reserve(values.size());
            for (auto& value : values)
                result.push_back(value);
            return result;
        }

        void reject_duplicate(const std::vector<string_view>& path) const
        {
            if (!_read_options.reject_duplicate_keys)
                return;
            if (_db.contains(std::span<const string_view>{ path.data(), path.size() }))
                throw std::logic_error("Duplicate JSON object key");
        }

        void ensure_not_array(const char* message) const
        {
            if (_array)
                throw std::logic_error(message);
        }

        template<class T>
        void set_value(T&& value)
        {
            if (!_pending_key)
                throw std::logic_error("JSON value is missing an object key");

            auto path = path_with_pending_key();
            reject_duplicate(path);
            _db.set(std::span<const string_view>{ path.data(), path.size() }, std::forward<T>(value));
            _pending_key.reset();
        }

        void convert_to_double()
        {
            if (_array->kind == array_kind::floating)
                return;

            _array->doubles.clear();
            _array->doubles.reserve(_array->ints.size() + _array->uints.size());
            for (auto value : _array->ints)
                _array->doubles.push_back(static_cast<double>(value));
            for (auto value : _array->uints)
                _array->doubles.push_back(static_cast<double>(value));
            _array->ints.clear();
            _array->uints.clear();
            _array->kind = array_kind::floating;
        }

        void append_int(std::int64_t value)
        {
            if (_array->kind == array_kind::none)
                _array->kind = array_kind::signed_int;
            if (_array->kind == array_kind::strings)
                throw std::logic_error("Mixed JSON arrays are not supported by the current json_db value model");
            if (_array->kind == array_kind::unsigned_int || _array->kind == array_kind::floating) {
                convert_to_double();
                _array->doubles.push_back(static_cast<double>(value));
                return;
            }
            _array->ints.push_back(value);
        }

        void append_uint(std::uint64_t value)
        {
            if (_array->kind == array_kind::none)
                _array->kind = array_kind::unsigned_int;
            if (_array->kind == array_kind::strings)
                throw std::logic_error("Mixed JSON arrays are not supported by the current json_db value model");
            if (_array->kind == array_kind::signed_int || _array->kind == array_kind::floating) {
                convert_to_double();
                _array->doubles.push_back(static_cast<double>(value));
                return;
            }
            _array->uints.push_back(value);
        }

        void append_double(double value)
        {
            if (_array->kind == array_kind::strings)
                throw std::logic_error("Mixed JSON arrays are not supported by the current json_db value model");
            convert_to_double();
            _array->doubles.push_back(value);
        }

        void append_string(string_view value)
        {
            if (_array->kind == array_kind::none)
                _array->kind = array_kind::strings;
            if (_array->kind != array_kind::strings)
                throw std::logic_error("Mixed JSON arrays are not supported by the current json_db value model");
            _array->strings.emplace_back(value);
        }

        db_type _db;
        json_read_options _read_options;
        std::vector<string_type> _path;
        std::optional<string_type> _pending_key;
        std::vector<object_state> _objects;
        std::optional<array_state> _array;
    };

    namespace detail
    {
        class json_writer
        {
        public:
            json_writer(const json_db& db, const json_write_options& options)
                : _db(db), _options(options)
            {}

            [[nodiscard]] std::string write()
            {
                write_object(json_db::root_node, 0);
                return std::move(_out).str();
            }

        private:
            [[nodiscard]] bool has_children(json_db::node_id node) const
            {
                return _db.tree().get_child(node) != json_db::invalid_node;
            }

            [[nodiscard]] std::vector<json_db::node_id> children(json_db::node_id node) const
            {
                std::vector<json_db::node_id> result;
                for (auto child = _db.tree().get_child(node); child != json_db::invalid_node; child = _db.tree().get_sibling(child))
                    result.push_back(child);
                if (_options.sort_keys) {
                    std::ranges::sort(result, [&](auto lhs, auto rhs) {
                        return _db.key(lhs) < _db.key(rhs);
                    });
                }
                return result;
            }

            void write_object(json_db::node_id node, std::uint32_t level)
            {
                auto child_nodes = children(node);
                _out << '{';
                if (!child_nodes.empty() && _options.pretty)
                    _out << '\n';

                for (std::size_t i = 0; i < child_nodes.size(); ++i) {
                    if (_options.pretty)
                        write_indent(level + 1);
                    write_string(_db.key(child_nodes[i]));
                    _out << ':';
                    if (_options.pretty)
                        _out << ' ';
                    write_node(child_nodes[i], level + 1);
                    if (i + 1 != child_nodes.size())
                        _out << ',';
                    if (_options.pretty)
                        _out << '\n';
                }

                if (!child_nodes.empty() && _options.pretty)
                    write_indent(level);
                _out << '}';
            }

            void write_node(json_db::node_id node, std::uint32_t level)
            {
                auto& value = _db.value(node);
                if (has_children(node)) {
                    if (!std::holds_alternative<std::monostate>(value))
                        throw std::logic_error("JSON writer cannot represent a node with both a value and child members");
                    write_object(node, level);
                    return;
                }
                write_value(value);
            }

            void write_value(const json_db::value_type& value)
            {
                std::visit([&](const auto& v) { write_variant(v); }, value);
            }

            void write_variant(std::monostate)
            {
                _out << "null";
            }

            void write_variant(bool value)
            {
                _out << (value ? "true" : "false");
            }

            void write_variant(std::int64_t value)
            {
                _out << value;
            }

            void write_variant(std::uint64_t value)
            {
                _out << value;
            }

            void write_variant(double value)
            {
                if (!std::isfinite(value))
                    throw std::logic_error("JSON writer cannot represent NaN or infinity");
                _out << std::setprecision((std::numeric_limits<double>::max_digits10)) << value;
            }

            void write_variant(json_db::string_ref ref)
            {
                write_string(_db.string(ref));
            }

            void write_variant(json_db::int_array_ref ref)
            {
                write_array(_db.array(ref));
            }

            void write_variant(json_db::uint_array_ref ref)
            {
                write_array(_db.array(ref));
            }

            void write_variant(json_db::double_array_ref ref)
            {
                auto values = _db.array(ref);
                _out << '[';
                for (std::size_t i = 0; i < values.size(); ++i) {
                    if (i != 0)
                        _out << ',';
                    write_variant(values[i]);
                }
                _out << ']';
            }

            void write_variant(json_db::string_array_ref ref)
            {
                auto values = _db.array(ref);
                _out << '[';
                for (std::size_t i = 0; i < values.size(); ++i) {
                    if (i != 0)
                        _out << ',';
                    write_string(_db.string(values[i]));
                }
                _out << ']';
            }

            void write_variant(json_db::blob_ref)
            {
                // JSON has no native byte-array type; keep blobs out of textual JSON until a project-specific encoding is chosen.
                throw std::logic_error("JSON writer does not support gbdb blob_ref values");
            }

            template<class T>
            void write_array(std::span<const T> values)
            {
                _out << '[';
                for (std::size_t i = 0; i < values.size(); ++i) {
                    if (i != 0)
                        _out << ',';
                    _out << values[i];
                }
                _out << ']';
            }

            void write_string(json_db::string_view value)
            {
                _out << '"';
                for (auto ch : value) {
                    switch (ch) {
                    case '"': _out << "\\\""; break;
                    case '\\': _out << "\\\\"; break;
                    case '\b': _out << "\\b"; break;
                    case '\f': _out << "\\f"; break;
                    case '\n': _out << "\\n"; break;
                    case '\r': _out << "\\r"; break;
                    case '\t': _out << "\\t"; break;
                    default:
                        if (static_cast<unsigned char>(ch) < 0x20 || (_options.ascii_only && static_cast<unsigned char>(ch) > 0x7f)) {
                            _out << "\\u" << std::hex << std::setw(4) << std::setfill('0') << static_cast<unsigned>(static_cast<unsigned char>(ch))
                                << std::dec << std::setfill(' ');
                        }
                        else {
                            _out << ch;
                        }
                        break;
                    }
                }
                _out << '"';
            }

            void write_indent(std::uint32_t level)
            {
                for (std::uint32_t i = 0; i < level * _options.indent; ++i)
                    _out << ' ';
            }

            const json_db& _db;
            const json_write_options& _options;
            std::ostringstream _out;
        };

#if GB_YADRO_GBDB_JSON_HAS_AXE
        class axe_json_reader
        {
        public:
            explicit axe_json_reader(std::string_view text, json_read_options options)
                : _text(text), _builder(options)
            {}

            [[nodiscard]] json_db parse()
            {
                using iterator = std::string_view::const_iterator;
                using namespace axe::shortcuts;

                auto json_hex = axe::r_many(axe::r_hex(), 4);
                auto json_escaped = "\""_axe | '\\' | '/' | 'b' | 'f' | 'n' | 'r' | 't' | 'u' & json_hex;
                auto json_char = _ - '"' - '\\' | '\\' & json_escaped;
                auto json_string = '"' & *json_char & '"';

                auto nonzero_digit = axe::r_any("123456789");
                auto int_part = axe::r_lit('0') | nonzero_digit & *_d;
                auto fraction = axe::r_lit('.') & +_d;
                auto exponent = axe::r_any("eE") & ~axe::r_any("+-") & +_d;
                auto json_number = ~axe::r_lit('-') & int_part & ~fraction & ~exponent;

                axe::r_rule<iterator> json_value;

                auto ws = *_ws;
                auto key = json_string >> [&](auto first, auto last) { _builder.key(decode_string(first, last)); };
                auto string_value = json_string >> [&](auto first, auto last) { _builder.string_value(decode_string(first, last)); };
                auto number_value = json_number >> [&](auto first, auto last) { store_number(first, last); };
                auto true_value = "true"_axe >> [&] { _builder.bool_value(true); };
                auto false_value = "false"_axe >> [&] { _builder.bool_value(false); };
                auto null_value = "null"_axe >> [&] { _builder.null_value(); };

                auto object_begin = axe::r_lit('{') >> [&] { _builder.begin_object(); };
                auto object_end = axe::r_lit('}') >> [&] { _builder.end_object(); };
                auto member = ws & key & ws & axe::r_lit(':') & ws & std::ref(json_value) & ws;
                auto object = object_begin & ws & ~(member % axe::r_lit(',')) & object_end;

                auto array_begin = axe::r_lit('[') >> [&] { _builder.begin_array(); };
                auto array_end = axe::r_lit(']') >> [&] { _builder.end_array(); };
                auto element = ws & std::ref(json_value) & ws;
                auto array = array_begin & ws & ~(element % axe::r_lit(',')) & array_end;

                json_value = string_value | number_value | object | array | true_value | false_value | null_value;

                auto document = ws & object & ws & _z
                    | axe::r_fail([&](auto, auto failed, auto) { fail_at("Failed to parse JSON object", failed); });

                auto result = axe::parse(document, _text.begin(), _text.end());
                if (!result)
                    fail_at("Failed to parse JSON object", result.position);
                return std::move(_builder).finish();
            }

        private:
            template<class Iterator>
            [[nodiscard]] std::string decode_string(Iterator first, Iterator last) const
            {
                if (first == last || *first != '"')
                    fail_at("Invalid JSON string", first);

                ++first;
                std::string result;
                while (first != last) {
                    auto ch = *first++;
                    if (ch == '"')
                        return result;
                    if (ch != '\\') {
                        result.push_back(ch);
                        continue;
                    }
                    if (first == last)
                        fail_at("Incomplete JSON string escape", first);
                    switch (*first++) {
                    case '"': result.push_back('"'); break;
                    case '\\': result.push_back('\\'); break;
                    case '/': result.push_back('/'); break;
                    case 'b': result.push_back('\b'); break;
                    case 'f': result.push_back('\f'); break;
                    case 'n': result.push_back('\n'); break;
                    case 'r': result.push_back('\r'); break;
                    case 't': result.push_back('\t'); break;
                    case 'u': append_utf8(parse_hex4(first, last), result); break;
                    default: fail_at("Invalid JSON string escape", first);
                    }
                }
                fail_at("Unterminated JSON string", first);
            }

            template<class Iterator>
            unsigned parse_hex4(Iterator& first, Iterator last) const
            {
                unsigned value = 0;
                for (int i = 0; i < 4; ++i) {
                    if (first == last)
                        fail_at("Incomplete JSON unicode escape", first);
                    auto ch = *first++;
                    value <<= 4;
                    if (ch >= '0' && ch <= '9')
                        value += static_cast<unsigned>(ch - '0');
                    else if (ch >= 'a' && ch <= 'f')
                        value += static_cast<unsigned>(ch - 'a' + 10);
                    else if (ch >= 'A' && ch <= 'F')
                        value += static_cast<unsigned>(ch - 'A' + 10);
                    else
                        fail_at("Invalid JSON unicode escape", first);
                }
                return value;
            }

            static void append_utf8(unsigned value, std::string& out)
            {
                if (value <= 0x7f) {
                    out.push_back(static_cast<char>(value));
                }
                else if (value <= 0x7ff) {
                    out.push_back(static_cast<char>(0xc0 | (value >> 6)));
                    out.push_back(static_cast<char>(0x80 | (value & 0x3f)));
                }
                else {
                    out.push_back(static_cast<char>(0xe0 | (value >> 12)));
                    out.push_back(static_cast<char>(0x80 | ((value >> 6) & 0x3f)));
                    out.push_back(static_cast<char>(0x80 | (value & 0x3f)));
                }
            }

            template<class Iterator>
            void store_number(Iterator first, Iterator last)
            {
                std::string token(first, last);
                auto floating = token.find_first_of(".eE") != std::string::npos;
                if (floating) {
                    double value{};
                    auto [ptr, ec] = std::from_chars(token.data(), token.data() + token.size(), value);
                    if (ec != std::errc{} || ptr != token.data() + token.size())
                        fail_at("JSON number is outside the double range", first);
                    _builder.double_value(value);
                }
                else if (!token.empty() && token.front() == '-') {
                    std::int64_t value{};
                    auto [ptr, ec] = std::from_chars(token.data(), token.data() + token.size(), value);
                    if (ec != std::errc{} || ptr != token.data() + token.size())
                        fail_at("JSON integer is outside the int64 range", first);
                    _builder.int_value(value);
                }
                else {
                    std::uint64_t value{};
                    auto [ptr, ec] = std::from_chars(token.data(), token.data() + token.size(), value);
                    if (ec != std::errc{} || ptr != token.data() + token.size())
                        fail_at("JSON integer is outside the uint64 range", first);
                    _builder.uint_value(value);
                }
            }

            template<class Iterator>
            [[noreturn]] void fail_at(std::string message, Iterator where) const
            {
                std::size_t offset = 0;
                std::uint32_t line = 1;
                std::uint32_t column = 1;

                if constexpr (requires { where - _text.begin(); }) {
                    offset = static_cast<std::size_t>(where - _text.begin());
                    for (auto it = _text.begin(); it != where; ++it) {
                        if (*it == '\n') {
                            ++line;
                            column = 1;
                        }
                        else {
                            ++column;
                        }
                    }
                }
                throw json_parse_error(std::move(message), offset, line, column);
            }

            std::string_view _text;
            json_db_builder _builder;
        };
#endif
    }

    [[nodiscard]] inline std::string write_json(const json_db& db, const json_write_options& options = {})
    {
        return detail::json_writer{ db, options }.write();
    }

    inline void write_json_file(const json_db& db, const std::filesystem::path& file, const json_write_options& options = {})
    {
        std::ofstream out(file, std::ios::binary);
        if (!out)
            throw std::runtime_error("Failed to open JSON file for writing");
        auto text = write_json(db, options);
        out.write(text.data(), static_cast<std::streamsize>(text.size()));
    }

    [[nodiscard]] inline json_db read_json(std::string_view text, const json_read_options& options = {})
    {
#if GB_YADRO_GBDB_JSON_HAS_AXE
        return detail::axe_json_reader{ text, options }.parse();
#else
        (void)text;
        throw std::logic_error("JSON reading requires opt-in AXE support: define GB_YADRO_ENABLE_AXE_JSON and add AXE include directory");
#endif
    }

    [[nodiscard]] inline json_db read_json_file(const std::filesystem::path& file, const json_read_options& options = {})
    {
        std::ifstream in(file, std::ios::binary);
        if (!in)
            throw std::runtime_error("Failed to open JSON file for reading");
        std::ostringstream buffer;
        buffer << in.rdbuf();
        return read_json(buffer.str(), options);
    }
}

#undef GB_YADRO_GBDB_JSON_HAS_AXE
