//-----------------------------------------------------------------------------
//  Copyright (C) 2026, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

#include <atomic>
#include <cassert>
#include <cstdint>
#include <functional>
#include <stdexcept>
#include <thread>
#include <concepts>
#include <type_traits>
#include <utility>
#include <vector>
#include <new>
#include "../util/traits.h"

#if defined(_MSC_VER) && (_MSC_VER <1950)
#error "msvc++ bug workaround see https://developercommunity.visualstudio.com/t/structured-binding-and-concept-fail-to-c/11033206"
#endif

namespace gb::yadro::container
{
    // Hash concept
    template<typename H, typename... Args>
    concept HashFunctor =
        std::is_nothrow_move_constructible_v<H> &&
        requires(H&& h, const Args&... args) {
            { std::invoke(std::forward<H>(h), args...) } -> std::convertible_to<std::pair<uint64_t, uint64_t>>;
    };

    // Function concept
    template<typename F, typename V, typename... Args>
    concept variadic_invocable =
        std::invocable<F&, Args...>&&
        std::convertible_to<std::invoke_result_t<F&, Args...>, V>;

    // state of memo table entry
    enum class State : uint8_t {
        empty,
        computing,
        ready
    };

    // mix64 function from MurmurHash3
    inline uint64_t mix64(uint64_t h) noexcept {
        h ^= h >> 33;
        h *= 0xff51afd7ed558ccdULL;
        h ^= h >> 33;
        h *= 0xc4ceb9fe1a85ec53ULL;
        h ^= h >> 33;
        return h;
    }

    // lock-free memoization table used to cache function results
    // in rare cases of hash collisions the value may be incorrect
    // lock-free memo table (variadic), primary template
    // if Value can't be deduced, specify it explicitly
    template<
        typename Hasher,
        typename Function,
        typename Value = util::callable_return_t<Function>
    >
    class lockfree_memo_table {
    private:
        struct alignas(std::hardware_destructive_interference_size) Entry {
            std::atomic<uint64_t> h_lo{ 0 };
            std::atomic<uint64_t> h_hi{ 0 };
            std::atomic<State> state{ State::empty };
            Value value{};
        
            Entry() = default;
            Entry(const Entry&) = delete;
            Entry& operator=(const Entry&) = delete;
        };

        mutable std::vector<Entry> table_;
        size_t mask_;
        size_t max_probe_;
        Hasher hasher_;
        Function func_;

    public:
        explicit lockfree_memo_table(
            size_t capacity,
            Function func,
            Hasher hasher = Hasher{},
            size_t max_probe = 64
        )
            : table_(capacity),
            mask_(capacity - 1),
            max_probe_(max_probe),
            hasher_(std::move(hasher)),
            func_(std::move(func))
        {
            if (capacity == 0 || (capacity & (capacity - 1)) != 0) {
                throw std::invalid_argument("capacity must be power of two");
            }
        }

        lockfree_memo_table(const lockfree_memo_table&) = delete;
        lockfree_memo_table& operator=(const lockfree_memo_table&) = delete;

        const Hasher& get_hasher() const { return hasher_; }

        // Variant that accepts pre-computed hash
        template<typename... Args>
            requires HashFunctor<Hasher, std::remove_cvref_t<Args>...>&&
        variadic_invocable<Function, Value, Args...>
            Value get_or_compute(Args&&... args) const
        {
            auto [h_lo, h_hi] = std::invoke(hasher_, args...);
            return get_or_compute_with_hash(h_lo, h_hi, std::forward<Args>(args)...);
        }

        template<typename... Args>
            requires HashFunctor<Hasher, std::remove_cvref_t<Args>...>&&
        variadic_invocable<Function, Value, Args...>
            Value get_or_compute_with_hash(uint64_t h_lo, uint64_t h_hi, Args&&... args) const
        {
            auto args_tuple = std::forward_as_tuple(std::forward<Args>(args)...);

            if ((h_lo | h_hi) == 0) {
                h_lo = 1;
            }

            size_t idx = mix64(h_lo) & mask_;

            for (size_t probe = 0; probe < max_probe_; ++probe) {
                Entry& e = table_[idx];

                uint64_t existing = e.h_lo.load(std::memory_order_acquire);

                // CASE 1: Slot is empty, try to claim it
                if (existing == 0) {
                    if (e.h_lo.compare_exchange_strong(
                        existing, h_lo,
                        std::memory_order_acq_rel,
                        std::memory_order_acquire))
                    {
                        // Successfully claimed
                        e.h_hi.store(h_hi, std::memory_order_relaxed);
                        e.state.store(State::computing, std::memory_order_release);

                        try {
                            e.value = std::apply([this](auto&&... stored_args) {
                                return std::invoke(func_,
                                    std::forward<decltype(stored_args)>(stored_args)...);
                                }, std::move(args_tuple));

                            e.state.store(State::ready, std::memory_order_release);
                            e.state.notify_all();
                            return e.value;
                        }
                        catch (...) {
                            // Notify waiters first
                            e.state.notify_all();

                            // Reset slot for retry
                            e.state.store(State::empty, std::memory_order_relaxed);
                            e.h_lo.store(0, std::memory_order_release);
                            throw;
                        }
                    }
                }
                // CASE 2: Slot might match our key
                else if (existing == h_lo &&
                    e.h_hi.load(std::memory_order_acquire) == h_hi)
                {
                    State current_state = e.state.load(std::memory_order_acquire);

                    while (current_state != State::ready) {
                        // Re-verify hash match (slot might have been reset/reclaimed)
                        if (e.h_lo.load(std::memory_order_acquire) != h_lo ||
                            e.h_hi.load(std::memory_order_acquire) != h_hi) {
                            goto next_probe;
                        }

                        e.state.wait(current_state, std::memory_order_acquire);
                        current_state = e.state.load(std::memory_order_acquire);
                    }

                    // Final verification before returning
                    if (e.h_lo.load(std::memory_order_acquire) == h_lo &&
                        e.h_hi.load(std::memory_order_acquire) == h_hi) {
                        return e.value;
                    }
                    // else: Hash changed between ready check and final verify, retry
                }

            next_probe:
                idx = (idx + 1) & mask_;
            }

            throw std::runtime_error("hash table probe limit exceeded");
        }
    };

    // Specialization for void-returning functions
    // 
    // DESIGN CHOICE (wait_for_completion parameter):
    // - false (default): Fire-and-forget semantics. Threads return immediately 
    //   upon finding a matching hash, even if State::computing. Maximizes 
    //   throughput for statistical workloads where occasional skipped evaluations
    //   are acceptable (e.g., Monte Carlo optimization, genetic algorithms).
    // - true: Guaranteed execution semantics. Threads wait until State::ready,
    //   ensuring the function completes successfully before any thread returns.
    //
    // EXCEPTION HANDLING:
    // If the computing thread throws, the slot is reset and other threads may
    // retry. With wait_for_completion=true, waiters detect the failure and retry.
    template<typename Hasher, typename Function>
    class lockfree_memo_table<Hasher, Function, void> {
    private:
        struct alignas(std::hardware_destructive_interference_size) Entry {
            std::atomic<uint64_t> h_lo{ 0 };
            std::atomic<uint64_t> h_hi{ 0 };
            std::atomic<State> state{ State::empty };

            Entry() = default;
            Entry(const Entry&) = delete;
            Entry& operator=(const Entry&) = delete;
        };

        mutable std::vector<Entry> table_;
        size_t mask_;
        size_t max_probe_;
        Hasher hasher_;
        Function func_;
        bool wait_for_completion_;

    public:
        explicit lockfree_memo_table(
            size_t capacity,
            Function func,
            Hasher hasher = Hasher{},
            size_t max_probe = 64,
            bool wait_for_completion = false
        )
            : table_(capacity),
            mask_(capacity - 1),
            max_probe_(max_probe),
            hasher_(std::move(hasher)),
            func_(std::move(func)),
            wait_for_completion_(wait_for_completion)
        {
            if (capacity == 0 || (capacity & (capacity - 1)) != 0) {
                throw std::invalid_argument("capacity must be power of two");
            }
        }

        const Hasher& get_hasher() const { return hasher_; }

        template<typename... Args>
            requires HashFunctor<Hasher, std::remove_cvref_t<Args>...>&&
        std::invocable<Function&, Args...>&&
            std::is_void_v<std::invoke_result_t<Function&, Args...>>
            void get_or_compute(Args&&... args) const
        {
            auto [h_lo, h_hi] = std::invoke(hasher_, args...);
            get_or_compute_with_hash(h_lo, h_hi, std::forward<Args>(args)...);
        }

        template<typename... Args>
            requires HashFunctor<Hasher, std::remove_cvref_t<Args>...>&&
        std::invocable<Function&, Args...>&&
            std::is_void_v<std::invoke_result_t<Function&, Args...>>
            void get_or_compute_with_hash(uint64_t h_lo, uint64_t h_hi, Args&&... args) const
        {
            auto args_tuple = std::forward_as_tuple(std::forward<Args>(args)...);

            if ((h_lo | h_hi) == 0) {
                h_lo = 1;
            }

            size_t idx = mix64(h_lo) & mask_;

            for (size_t probe = 0; probe < max_probe_; ++probe) {
                Entry& e = table_[idx];

                uint64_t existing = e.h_lo.load(std::memory_order_acquire);

                // CASE 1: Slot is empty, try to claim it
                if (existing == 0) {
                    if (e.h_lo.compare_exchange_strong(
                        existing, h_lo,
                        std::memory_order_acq_rel,
                        std::memory_order_acquire))
                    {
                        // Successfully claimed
                        e.h_hi.store(h_hi, std::memory_order_relaxed);
                        e.state.store(State::computing, std::memory_order_release);

                        try {
                            std::apply([this](auto&&... stored_args) {
                                std::invoke(func_,
                                    std::forward<decltype(stored_args)>(stored_args)...);
                                }, std::move(args_tuple));

                            e.state.store(State::ready, std::memory_order_release);
                            e.state.notify_all();
                            return;
                        }
                        catch (...) {
                            // Notify waiters first (before resetting state)
                            e.state.notify_all();

                            // Reset slot so another thread may retry
                            e.state.store(State::empty, std::memory_order_relaxed);
                            e.h_lo.store(0, std::memory_order_release);
                            throw;
                        }
                    }
                }
                // CASE 2: Slot might match our key
                else if (existing == h_lo &&
                    e.h_hi.load(std::memory_order_acquire) == h_hi)
                {
                    if (wait_for_completion_) {
                        // Wait for computation to complete
                        State current_state = e.state.load(std::memory_order_acquire);

                        while (current_state != State::ready) {
                            // Re-verify hash match (slot might have been reset/reclaimed)
                            if (e.h_lo.load(std::memory_order_acquire) != h_lo ||
                                e.h_hi.load(std::memory_order_acquire) != h_hi) {
                                goto next_probe;  // Hash changed, retry probing
                            }

                            e.state.wait(current_state, std::memory_order_acquire);
                            current_state = e.state.load(std::memory_order_acquire);
                        }

                        // Final verification before returning
                        // (ensure we're still looking at the right entry)
                        if (e.h_lo.load(std::memory_order_acquire) != h_lo ||
                            e.h_hi.load(std::memory_order_acquire) != h_hi) {
                            goto next_probe;
                        }
                    }
                    // else: Fire-and-forget mode - return immediately regardless of state

                    return;
                }

            next_probe:
                idx = (idx + 1) & mask_;
            }

            throw std::runtime_error("hash table probe limit exceeded");
        }
    };

    /**
     * Sharded lock-free memoization table for high-concurrency workloads.
     *
     * DESIGN:
     * - Divides hash space into NumShards independent tables
     * - Uses high bits of hash for shard selection (via mix64)
     * - Each shard uses original hash for internal probing
     * - Single hasher shared across all shards (computed once per lookup)
     * - Eliminates cross-shard contention for near-linear scaling
     *
     * PERFORMANCE:
     * - Scales linearly up to NumShards concurrent threads
     * - Recommended: NumShards = 2x core count (default 64 for 32-core systems)
     * - Each shard independently allocated to prevent false sharing
     * - Single hash computation per lookup (no redundant hashing)
     *
     * REQUIREMENTS:
     * - total_capacity must be power of 2
     * - NumShards must be power of 2
     * - Function must be copyable (replicated per shard for thread-safety)
     * - Hasher must return std::pair<uint64_t, uint64_t>
     */
    template<
        typename Hasher,
        typename Function,
        typename Value = util::callable_return_t<Function>,
        size_t NumShards = 64  // Power of 2, typically 2x core count
            >
        class ShardedLockFreeMemoTable {
        static_assert((NumShards& (NumShards - 1)) == 0,
            "NumShards must be a power of two");
        static_assert(NumShards > 0,
            "NumShards must be greater than zero");
        static_assert(std::is_copy_constructible_v<Function>,
            "Function must be copyable (replicated per shard)");

        private:
            using InternalTable = lockfree_memo_table<Hasher, Function, Value>;

            // Single hasher instance shared for all lookups
            Hasher hasher_;

            // Array of unique_ptrs ensures independent allocation
            // preventing false sharing between shard metadata
            std::array<std::unique_ptr<InternalTable>, NumShards> shards_;

            static constexpr size_t ShardMask = NumShards - 1;

        public:
            /**
             * Constructs a sharded memoization table.
             *
             * @param total_capacity Total entries across all shards. Must be power of 2.
             *                       Will be divided equally among shards.
             * @param func Function to memoize. Copied to each shard for thread-safety.
             * @param hasher Hash function. Must return std::pair<uint64_t, uint64_t>.
             * @param max_probe Maximum linear probing distance within each shard.
             *
             * @throws std::invalid_argument if total_capacity is not power of 2
             * @throws std::invalid_argument if total_capacity < NumShards
             */
            explicit ShardedLockFreeMemoTable(
                size_t total_capacity,
                Function func,
                Hasher hasher = Hasher{},
                size_t max_probe = 64
            ) : hasher_(std::move(hasher))
            {
                // Validate total capacity
                if (total_capacity == 0 || (total_capacity & (total_capacity - 1)) != 0) {
                    throw std::invalid_argument(
                        "total_capacity must be a power of two"
                    );
                }

                if (total_capacity < NumShards) {
                    throw std::invalid_argument(
                        "total_capacity must be at least NumShards"
                    );
                }

                size_t capacity_per_shard = total_capacity / NumShards;

                // Verify capacity_per_shard is power of 2
                // (automatic if both total_capacity and NumShards are powers of 2)
                assert((capacity_per_shard & (capacity_per_shard - 1)) == 0 &&
                    "capacity_per_shard must be power of two");

                // Create each shard with independent allocation
                // Function is copied to each shard for thread-safety
                // Hasher is copied to each shard (typically cheap/stateless)
                for (size_t i = 0; i < NumShards; ++i) {
                    shards_[i] = std::make_unique<InternalTable>(
                        capacity_per_shard,
                        func,      // Copy function to each shard
                        hasher_,   // Copy hasher to each shard
                        max_probe
                    );
                }
            }

            /**
             * Get or compute memoized value.
             *
             * Thread-safe. Multiple threads can call concurrently.
             * If the value exists, returns immediately.
             * If computing, waits for completion (unless void specialization with wait=false).
             * If not present, exactly one thread computes while others wait.
             *
             * @param args Arguments to hash and pass to the function
             * @return Computed or cached value
             * @throws std::runtime_error if probe limit exceeded in selected shard
             * @throws Any exception thrown by Function
             */
            template<typename... Args>
                requires HashFunctor<Hasher, std::remove_cvref_t<Args>...>&&
            variadic_invocable<Function, Value, Args...>
                Value get_or_compute(Args&&... args) const
            {
                // Compute hash once using shared hasher
                // Hasher takes const references, so no moves occur here
                auto [h_lo, h_hi] = std::invoke(hasher_, args...);

                // Select shard using high-quality mixing of h_hi
                // mix64 ensures good distribution even if h_hi has patterns
                // Use h_hi (not h_lo) to keep h_lo available for internal probing
                size_t shard_idx = mix64(h_hi) & ShardMask;

                // Delegate to selected shard with pre-computed hash
                // This avoids redundant hashing inside the shard
                return shards_[shard_idx]->get_or_compute_with_hash(
                    h_lo,
                    h_hi,
                    std::forward<Args>(args)...
                );
            }

            /**
             * Access the hasher instance.
             * Useful for testing or pre-computing hashes.
             */
            const Hasher& get_hasher() const noexcept {
                return hasher_;
            }

            /**
             * Get the number of shards.
             */
            static constexpr size_t num_shards() noexcept {
                return NumShards;
            }

            /**
             * Get capacity per shard.
             * Total capacity is this value * NumShards.
             */
            size_t capacity_per_shard() const noexcept {
                return shards_[0] ? shards_[0]->capacity() : 0;
            }

            /**
             * Get total capacity across all shards.
             */
            size_t total_capacity() const noexcept {
                return capacity_per_shard() * NumShards;
            }
    };

    /**
     * Specialization for void-returning functions.
     * Supports fire-and-forget mode (default) or guaranteed completion mode.
     */
    template<
        typename Hasher,
        typename Function,
        size_t NumShards
                >
        class ShardedLockFreeMemoTable<Hasher, Function, void, NumShards> {
        static_assert((NumShards& (NumShards - 1)) == 0,
            "NumShards must be a power of two");
        static_assert(NumShards > 0,
            "NumShards must be greater than zero");
        static_assert(std::is_copy_constructible_v<Function>,
            "Function must be copyable (replicated per shard)");

        private:
            using InternalTable = lockfree_memo_table<Hasher, Function, void>;

            Hasher hasher_;
            std::array<std::unique_ptr<InternalTable>, NumShards> shards_;

            static constexpr size_t ShardMask = NumShards - 1;

        public:
            /**
             * Constructs a sharded memoization table for void functions.
             *
             * @param total_capacity Total entries across all shards. Must be power of 2.
             * @param func Function to memoize (void return type).
             * @param hasher Hash function.
             * @param max_probe Maximum linear probing distance within each shard.
             * @param wait_for_completion If true, threads wait for computation to complete.
             *                            If false (default), threads return immediately on hash match
             *                            even if computation is in progress (fire-and-forget).
             */
            explicit ShardedLockFreeMemoTable(
                size_t total_capacity,
                Function func,
                Hasher hasher = Hasher{},
                size_t max_probe = 64,
                bool wait_for_completion = false
            ) : hasher_(std::move(hasher))
            {
                if (total_capacity == 0 || (total_capacity & (total_capacity - 1)) != 0) {
                    throw std::invalid_argument(
                        "total_capacity must be a power of two"
                    );
                }

                if (total_capacity < NumShards) {
                    throw std::invalid_argument(
                        "total_capacity must be at least NumShards"
                    );
                }

                size_t capacity_per_shard = total_capacity / NumShards;
                assert((capacity_per_shard & (capacity_per_shard - 1)) == 0);

                for (size_t i = 0; i < NumShards; ++i) {
                    shards_[i] = std::make_unique<InternalTable>(
                        capacity_per_shard,
                        func,
                        hasher_,
                        max_probe,
                        wait_for_completion  // Pass through to each shard
                    );
                }
            }

            template<typename... Args>
                requires HashFunctor<Hasher, std::remove_cvref_t<Args>...>&&
            std::invocable<Function&, Args...>&&
                std::is_void_v<std::invoke_result_t<Function&, Args...>>
                void get_or_compute(Args&&... args) const
            {
                auto [h_lo, h_hi] = std::invoke(hasher_, args...);
                size_t shard_idx = mix64(h_hi) & ShardMask;

                shards_[shard_idx]->get_or_compute_with_hash(
                    h_lo,
                    h_hi,
                    std::forward<Args>(args)...
                );
            }

            const Hasher& get_hasher() const noexcept {
                return hasher_;
            }

            static constexpr size_t num_shards() noexcept {
                return NumShards;
            }

            size_t capacity_per_shard() const noexcept {
                return shards_[0] ? shards_[0]->capacity() : 0;
            }

            size_t total_capacity() const noexcept {
                return capacity_per_shard() * NumShards;
            }
    };
}
