//-----------------------------------------------------------------------------
//  Copyright (C) 2026, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once
#include <vector>
#include <set>
#include <algorithm>
#include <ranges>
#include <concepts>
#include <immintrin.h>

/**
 * @file pareto_front.h
 *
 * @brief Pareto-front filtering for multi-objective selection of financial time-series statistics.
 *
 * This header provides three container classes for maintaining a Pareto-optimal set of
 * candidates described by the `basic_stats` concept (mean, Sharpe, Sortino, drawdown,
 * tail risk, and related metrics). A candidate is retained only if no other candidate
 * dominates it across all configured objectives simultaneously.
 *
 * ---------------------------------------------------------------------------
 * CONTAINERS
 * ---------------------------------------------------------------------------
 *
 *  pareto_set<T, Dominates>
 *      Flat vector-backed Pareto front. Suitable for batch insertion and iteration.
 *      Supports post-hoc `resize()` to trim the front by any projected metric.
 *      O(n) per insertion.
 *
 *  pareto_set_ordered<T, Dominates, KeyProj>
 *      As above, but elements are maintained in descending order of a chosen
 *      projection (KeyProj). Enables a caller-supplied `no_further_dominators`
 *      predicate to short-circuit the dominance scan when ordering guarantees
 *      no subsequent element can dominate the candidate.
 *      O(n) per insertion; O(log n) ordered access.
 *
 *      Precondition on `no_further_dominators`: once it returns true for a pair
 *      (candidate, set_element), no element later in iteration order may dominate
 *      the candidate. Violating this precondition silently produces an incorrect
 *      Pareto front.
 *
 *  simd::pareto_set<S, Dominates>
 *      Two-stage filter that uses AVX2 SIMD instructions for fast rejection on
 *      four fixed objectives before falling back to full exact dominance via Dominates.
 *
 *      *** NOT AN EXACT PARETO FILTER ***
 *      A candidate that dominates on objectives outside the four SIMD metrics
 *      will be incorrectly rejected by the SIMD stage. Use this class only when
 *      those four objectives are the primary discriminators and approximate
 *      results are acceptable. For exact results use pareto_set or
 *      pareto_set_ordered.
 *
 *      Requires AVX2 support (-mavx2 / /arch:AVX2). Behaviour is undefined on
 *      hardware that does not support AVX2.
 *
 * ---------------------------------------------------------------------------
 * OBJECTIVES AND DOMINANCE
 * ---------------------------------------------------------------------------
 *
 *  objective_t<Proj, Dir, Eps>
 *      Binds a projection (T → double), an optimization direction (maximize_t or
 *      minimize_t), and an epsilon for near-equality tolerance into a single
 *      comparator unit. Epsilon defaults to 1e-6.
 *
 *  dominates_t<Objs...>
 *      Combines any number of objective_t instances via a compile-time fold.
 *      Candidate `a` dominates `b` iff `a` is not worse on every objective
 *      and strictly better on at least one.
 *
 * ---------------------------------------------------------------------------
 * LIMITATIONS
 * ---------------------------------------------------------------------------
 *
 *  - Insertion is O(n) in the current front size for all containers; no
 *    spatial indexing is performed. Performance degrades for large fronts
 *    (> ~10 000 elements).
 *
 *  - pareto_set and simd::pareto_set do not maintain insertion order after
 *    `resize()` — element ordering is unspecified following that call.
 *
 *  - All containers store elements by value. T must be copyable.
 *
 *  - `insert` overloads may throw `std::bad_alloc` on memory exhaustion;
 *    they are not `noexcept`.
 *
 *  - simd::pareto_set requires T to satisfy `basic_stats` at the
 *    insert call site; the template parameter S must also satisfy `basic_stats`.
 *
 *  - Thread safety: none. External synchronisation is required for concurrent
 *    insertion or iteration.
 */

namespace gb::yadro::container
{
    // epsilon used for reducing effect of noisy statistics
    inline constexpr double default_epsilon = 1e-6;

    // some statistical parameters need to be maximized, some minimized
    struct maximize_t;
    struct minimize_t;

    template<class Dir>
    concept max_or_min_direction = std::same_as<Dir, maximize_t> || std::same_as<Dir, minimize_t>;

    static_assert(max_or_min_direction<maximize_t>);
    static_assert(max_or_min_direction<minimize_t>);
    
    //-------------------------------------------------------------------------
    // An objective_t is:
    //  a projection Proj(maps T -> double)
    //  a direction(maximize / minimize)
    //  epsilon - small double value that indicates values are almost equal
    //-------------------------------------------------------------------------

    template<typename Proj, max_or_min_direction Dir, double Eps = default_epsilon>
    struct objective_t
    {
        Proj proj;
        static constexpr auto epsilon() { return Eps; }

        using Projection = Proj;
        using Direction = Dir;

        template<typename T>
        auto value(const T& x) const noexcept { return std::invoke(proj, x); }

        template<typename T>
        bool compare(const T& a, const T& b, bool& better) const noexcept
        {
            auto va = value(a);
            auto vb = value(b);

            if constexpr (std::same_as<Dir, maximize_t>)
            {
                if (va + Eps < vb) return false;
                if (va > vb + Eps) better = true;
            }
            else
            {
                if (va > vb + Eps) return false;
                if (va + Eps < vb) better = true;
            }
            return true;
        }
    };

    //-------------------------------------------------------------------------
    // Dominance (compile-time fold)
    // determines which statistics dominates the other
    //-------------------------------------------------------------------------

    template<typename... Objs>
    class dominates_t
    {
        static_assert(sizeof...(Objs) != 0);

        using ObjTuple = std::tuple<Objs...>;
        ObjTuple objs;

    public:
        template<size_t N>
        using Objective = std::tuple_element_t<N, ObjTuple>;
        
        template<size_t N>
        using Direction = typename Objective<N>::Direction;

        template<size_t N>
        using Projection = typename Objective<N>::Projection;

        static constexpr size_t number_of_objectives = sizeof...(Objs);
        static constexpr double min_epsilon = std::min({ Objs::epsilon()... });

        // int directions used in SIMD version: +1 - maximize, -1 - minimize
        static constexpr std::array< int, number_of_objectives> int_directions{ (std::is_same_v<typename Objs::Direction, maximize_t> ? 1 : -1)... };
        
        template<size_t N>
        constexpr const auto& get_proj() const noexcept { return std::get<N>(objs).proj; }

        template<size_t N>
        constexpr auto get_proj(auto&& stat) const noexcept { return std::invoke(std::get<N>(objs).proj, stat); }

        // constructors
        dominates_t() = default;
        explicit dominates_t(Objs&&... os) : objs(std::forward<Objs>(os)...) {}

        // comparison returns true if it's better in at least one objective and not worse in the rest
        template<typename T>
        bool operator()(const T& a, const T& b) const noexcept
        {
            bool better_in_any = false;

            return std::apply([&](const auto&... o) {
                return ((o.compare(a, b, better_in_any)) && ...) && better_in_any;
                }, objs);
        }
    };

    //-------------------------------------------------------------------------
    // Pareto container (flat)
    //-------------------------------------------------------------------------

    template<typename T, typename Dominates>
    class pareto_set
    {
        std::vector<T> data_;
        Dominates dominates_;

    public:
        pareto_set() = default;
        explicit pareto_set(Dominates d) : dominates_(std::move(d)) {}

        auto& get_dominates() const noexcept { return dominates_; }

        void insert(const std::ranges::range auto& r)
        {
            for (auto& v : r)
                insert(v);
        }

        bool insert(const T& x)
        {
            // reject if dominated
            for (const auto& y : data_)
                if (dominates_(y, x))
                    return false;

            // erase dominated
            data_.erase(
                std::remove_if(data_.begin(), data_.end(),
                    [&](const T& y) { return dominates_(x, y); }),
                data_.end()
            );

            data_.push_back(x);
            return true;
        }

        // first objective is used for resizing
        void resize(std::size_t n) noexcept
        {
            if (data_.size() <= n) return;

            using Dir = typename Dominates::template Direction<0>;
            auto& proj = dominates_.get_proj<0>();

            std::nth_element(data_.begin(), data_.begin() + n, data_.end(),
                [&](const T& a, const T& b) {
                    if constexpr (std::same_as<Dir, maximize_t>)
                        return proj(a) > proj(b);
                    else
                        return proj(a) < proj(b);
                });

            data_.resize(n);
        }

        const std::vector<T>& elements() const noexcept { return data_; }

        void clear() noexcept { data_.clear(); }
    };

    template<typename S, typename Dominates>
    inline auto make_pareto_set(Dominates d) { return pareto_set<S, Dominates>(std::move(d)); }

    //-------------------------------------------------------------------------
    // Pareto container (sorted by KeyProj)
    // ATTN: much slower than unordered container, has some comparison issues
    // ATTN: quick reject can present issues
    // ATTN: not recommended
    //-------------------------------------------------------------------------

    template<typename T, typename Dominates>
    class pareto_set_ordered
    {
        struct cmp
        {
            typename Dominates::template Projection<0> proj;
            // comparison isn't entirely correct, addresses would change on copying
            bool operator()(const T& a, const T& b) const
            {
                auto ka = proj(a);
                auto kb = proj(b);
                if (ka != kb) return ka > kb;          // primary: descending by projection
                return std::addressof(a) < std::addressof(b); // secondary: pointer tiebreak
            }
        };

        std::set<T, cmp> data_;
        Dominates dominates_;

    public:
        pareto_set_ordered() = default;
        
        explicit pareto_set_ordered(Dominates d)
            : data_(cmp{ d.get_proj0()}), dominates_(std::move(d)) {}

        auto& get_dominates() const noexcept { return dominates_; }

        void insert(const std::ranges::range auto& r)
        {
            for (auto& v : r)
                insert(v);
        }

        void insert(const std::ranges::range auto& r, auto&& quick_reject)
        {
            for (auto& v : r)
                insert(v, decltype(quick_reject)(quick_reject));
        }

        bool insert(const T& x) noexcept
        {
            for (const auto& y : data_)
                if (dominates_(y, x))
                    return false;

            // remove dominated
            for (auto it = data_.begin(); it != data_.end(); )
            {
                if (dominates_(x, *it))
                    it = data_.erase(it);
                else
                    ++it;
            }

            data_.insert(x);
            return true;
        }

        // This is only valid when data_ is ordered by a key that bounds dominance
        // (e.g. descending by the projection used as KeyProj).
        bool insert(const T& x, auto&& no_further_dominators) noexcept
            requires requires{ {std::invoke(no_further_dominators, x, x)}->std::convertible_to<bool>; }
        {
            for (const auto& y : data_)
            {
                if (dominates_(y, x))
                    return false;

                // Precondition: once this returns true, no element remaining
                // in iteration order can dominate x (caller's responsibility).
                if (std::invoke(no_further_dominators, x, y))
                    break;
            }

            for (auto it = data_.begin(); it != data_.end(); )
            {
                if (dominates_(x, *it))
                    it = data_.erase(it);
                else
                    ++it;
            }

            data_.insert(x);
            return true;
        }

        void resize(std::size_t n) noexcept
        {
            if (n >= data_.size()) return;
            auto it = data_.begin();
            std::advance(it, n);
            data_.erase(it, data_.end());
        }

        const auto& elements() const noexcept { return data_; }
    };

    template<typename S, typename Dominates>
    inline auto make_pareto_set_ordered(Dominates d) { return pareto_set_ordered<S, Dominates>(std::move(d)); }

    namespace simd
    {
        template<size_t N>
        struct alignas(32) obj_vec_t
        {
            std::array<double, N> v;
        };

        using vec4 = obj_vec_t<4>;

        //---------------------------------------------------------------------
        inline bool dominates_avx2_eps(const vec4& a, const vec4& b, double eps)
        {
            __m256d va = _mm256_load_pd(a.v.data());
            __m256d vb = _mm256_load_pd(b.v.data());
            __m256d ve = _mm256_set1_pd(eps);

            // va + eps >= vb
            __m256d va_eps = _mm256_add_pd(va, ve);
            __m256d ge = _mm256_cmp_pd(va_eps, vb, _CMP_GE_OQ);

            // va > vb + eps
            __m256d vb_eps = _mm256_add_pd(vb, ve);
            __m256d gt = _mm256_cmp_pd(va, vb_eps, _CMP_GT_OQ);

            int ge_mask = _mm256_movemask_pd(ge);
            int gt_mask = _mm256_movemask_pd(gt);

            if (ge_mask != 0b1111)
                return false;

            return gt_mask != 0;
        }

        // values: -1 - minimize, +1 - maximize
        template<int lane0, int lane1, int lane2, int lane3>
        inline vec4 apply_mask(const vec4& x)
        {
            __m256d v = _mm256_load_pd(x.v.data());
            // _mm256_set_pd fills (lane3, lane2, lane1, lane0)
            // Negate minimize objectives so all four become "maximize"
            __m256d m = _mm256_set_pd(lane3, lane2, lane1, lane0);

            __m256d r = _mm256_mul_pd(v, m);

            vec4 out;
            _mm256_store_pd(out.v.data(), r);
            return out;
        }

        // four or more objectives
        template<typename S, typename Dominates>
        class pareto_set
        {
            static_assert(Dominates::number_of_objectives > 3);

            struct pareto_node
            {
                S stats;
                vec4 vec;
            };

            std::vector<pareto_node> data_;
            Dominates dom;

            static constexpr auto eps = Dominates::min_epsilon;

            template<max_or_min_direction Dir>
            static constexpr int get_direction() {
                return std::same_as<Dir, maximize_t> ? 1 : -1;
            }

        public:
            pareto_set() = default;
            explicit pareto_set(auto&&... args) : dom(decltype(args)(args)) {}

            auto& get_dominates() const noexcept { return dom; }

            void insert(const std::ranges::range auto& r)
            {
                for (auto& v : r)
                    insert(v);
            }

            bool insert(const S& s)
            {
                pareto_node x{ s, project_stats(s) };

                // --- reject if dominated ---
                for (const auto& y : data_)
                {
                    if (dominates(y, x))
                        return false;
                }

                // --- remove dominated ---
                data_.erase(
                    std::remove_if(data_.begin(), data_.end(),
                        [&](const auto& y)
                        {
                            return dominates(x, y);
                        }),
                    data_.end()
                );

                data_.push_back(x);
                return true;
            }

            auto elements() const
            {
                std::vector<S> out;
                out.reserve(data_.size());
                for (auto& x : data_)
                    out.push_back(x.stats);
                return out;
            }

            // first objective is used for resizing
            void resize(std::size_t n) noexcept
            {
                if (data_.size() <= n) return;
                auto& proj = dom.get_proj<0>();
                using Dir = typename Dominates::template Direction<0>;

                std::nth_element(data_.begin(), data_.begin() + n, data_.end(),
                    [&](const auto& a, const auto& b) {
                        if constexpr (std::same_as<Dir, maximize_t>)
                            return proj(a.stats) > proj(b.stats);
                        else
                            return proj(a.stats) < proj(b.stats);
                    });

                data_.resize(n);
            }

            void clear() noexcept { data_.clear(); }

        private:
            // SIMD only dominance
            template<int lane0, int lane1, int lane2, int lane3>
            static bool dominates_simd(const vec4& a_raw, const vec4& b_raw, double eps)
            {
                vec4 a = apply_mask < lane0, lane1, lane2, lane3 >(a_raw);
                vec4 b = apply_mask < lane0, lane1, lane2, lane3 >(b_raw);

                return dominates_avx2_eps(a, b, eps);
            }

            bool dominates(const pareto_node& a, const pareto_node& b)
            {
                // Stage 0: 4 objectives fit SIMD, nothing else is necessary
                if constexpr (Dominates::number_of_objectives == 4)
                    return dominates_simd<
                    Dominates::int_directions[0],
                    Dominates::int_directions[1],
                    Dominates::int_directions[2],
                    Dominates::int_directions[3]
                    >(a.vec, b.vec, eps);

                // Stage 1: SIMD quick rejection
                if (!dominates_simd<
                    Dominates::int_directions[0],
                    Dominates::int_directions[1],
                    Dominates::int_directions[2],
                    Dominates::int_directions[3]
                >(a.vec, b.vec, eps))
                    return false;

                // Stage 2: exact validation
                return dom(a.stats, b.stats);
            }

            vec4 project_stats(const S& s)
            {
                return vec4{
                    dom.get_proj<0>(s),
                    dom.get_proj<1>(s),
                    dom.get_proj<2>(s),
                    dom.get_proj<3>(s),
                };
            }
        };

        template<typename S, typename Dominates>
        inline auto make_pareto_set(Dominates d) { return simd::pareto_set<S, Dominates>(std::move(d)); }
    }
}