//-----------------------------------------------------------------------------
//  Copyright (C) 2024, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

#include <vector>
#include <exception>
#include <iostream>
#include <functional>
#include <queue>
#include <map>
#include <string>
#include <utility>

#include "task.h"
#include "fiber.h"

namespace gb::sim
{
    struct event_base
    {
        void trigger()
        {
            for (auto&& cb : _call_backs) std::invoke(cb);
            for (auto cancellable = std::move(_cancellable); auto && [_, fun] : cancellable) { std::invoke(fun); }
            for (auto c_once = std::move(_call_once); auto&&  f : c_once) { std::invoke(f); }
        }

        void schedule(auto& scheduler, auto sim_time = 0)
        {
            scheduler([this] { this->trigger(); }, sim_time);
        }

        void bind(auto&& ... functions) { (_call_backs.push_back(decltype(functions)(functions)), ...); }
        void bind_once(auto&& ... functions) { (_call_once.push_back(decltype(functions)(functions)), ...); }
        void bind_cancellable(void* p, auto&& f) requires requires{std::invoke(f); } { _cancellable.emplace_back(p, decltype(f)(f)); }
        void cancel_wait(void* p) { std::erase_if(_cancellable, [p](auto&& ptr_rec) { return p == ptr_rec.first; }); }
        void cancel_wait() { _cancellable.clear(); _call_once.clear(); }
        void clear() { _cancellable.clear(); _call_once.clear(); _call_backs.clear(); }

    private:
        std::vector<std::pair<void*, std::function<void()>>> _cancellable;
        std::vector<std::function<void()>> _call_backs;
        std::vector<std::function<void()>> _call_once;
    };

    inline void clear_events(auto&& ...e) { (e.clear(), ...); }
}

namespace gb::sim::coroutines
{
    //---------------------------------------------------------------------------------------------
    struct event : event_base
    {
        // awaitable interface
        void await_suspend(auto h) { bind_once([h = std::move(h)] { h.resume(); }); }
        void await_resume() {}
        auto await_ready() { return false; }
    };

    //---------------------------------------------------------------------------------------------
    // waiter on list of events, resumes on first triggered event and cancells all callbacks
    template<class ...E>
    struct any_of
    {
        any_of(E&& ...e) : _events(std::forward<E>(e)...)
        {
        }

        void bind_cancellable(void* p, auto&& f)
        {
            std::apply([=, this](auto& ...e)
                {
                    (e.bind_cancellable(p, f), ...);
                }, _events);
        }

        void cancel_wait(void* p)
        {
            std::apply([p](auto& ...e)
                {
                    (e.cancel_wait(p), ...);
                }, _events);
        }

        void await_suspend(auto h)
        {
            std::apply([this, h](auto& ...e)
                {
                    (e.bind_cancellable(this, [h]
                        {
                            h.resume();
                        }), ...);
                }, _events);
        }

        void await_resume() { cancel_wait(this); }
        auto await_ready() { return false; }

    private:
        std::tuple<E...> _events;
    };

    template<class ...E>
    any_of(E&&...) -> any_of<E...>;

    //---------------------------------------------------------------------------------------------
    // waiter for all events to be triggered in any order
    template<class ...E>
    struct all_of
    {
        all_of(E&& ...e) : _events(std::tuple{ std::tuple<E, bool>{ std::forward<E>(e), false }... }) { }

        void bind_cancellable(void* p, auto&& f)
        {
            std::apply([=, this](auto& ...e)
                {
                    (std::get<0>(e).bind_cancellable(p, f), ...);
                }, _events);
        }

        void cancel_wait(void* p)
        {
            std::apply([=](auto& ...e)
                {
                    (std::get<0>(e).cancel_wait(p), ...);
                }, _events);
        }

        void await_suspend(auto h)
        {
            std::apply([this, h](auto& ...ep)
                {
                    (std::get<0>(ep).bind_cancellable(this,
                        [this, h, &ep]
                        {
                            std::get<1>(ep) = true;
                            if (all_ready())
                                h.resume();
                        }), ...);
                }, _events);
        }

        void await_resume() { cancel_wait(this); }
        auto await_ready() { return false; }

    private:
        std::tuple<std::tuple<E, bool>...> _events;

        bool all_ready()
        {
            return std::apply([](auto&& ...ep)
                {
                    return (std::get<1>(ep) && ...);
                }, _events);
        }
    };

    template<class ...E>
    all_of(E&& ...) -> all_of<E...>;

    //---------------------------------------------------------------------------------------------
    struct empty_event
    {
        void trigger() {}
        void schedule(auto&&...) {}
        void bind(auto&& ...) {}
        void bind_once(auto&& ...) {}
        void bind_cancellable(auto&&...) {}
        void cancel_wait(auto&&...) {}
        void await_suspend(auto h) {}
        void await_resume() {}
        auto await_ready() { return true; }
    };
}

//-------------------------------------------------------------------------------------------------
namespace gb::sim::fibers
{
    using event = event_base;
    //---------------------------------------------------------------------------------------------
    // waiter on list of events, resumes on first triggered event and cancells all callbacks
    template<class ...E>
    struct any_of
    {
        any_of(E&& ...e) : _events(std::forward<E>(e)...)
        {
        }
        
        void bind_once(auto call_back)
        {
            bind_cancellable(this, [this, call_back]
                {
                    cancel_wait(this);
                    std::invoke(call_back);
                });
        }
        
        void bind_cancellable(void* p, auto&& f)
        {
            std::apply([=, this](auto& ...e)
                {
                    (e.bind_cancellable(p, f), ...);
                }, _events);
        }
        
        void cancel_wait(void* p) 
        { 
            std::apply([=](auto& ...e)
                {
                    (e.cancel_wait(p), ...);
                }, _events);
        }
    private:
        std::tuple<E...> _events;
    };

    inline void wait_any(auto&& ... e)
    {
        wait(any_of{ decltype(e)(e)... });
    }

    template<class ...E>
    any_of(E&&...) -> any_of<E...>;

    template<class E1, class E2>
        requires requires { std::declval<E1>().bind_cancellable(0,0); std::declval<E2>().bind_cancellable(0, 0); }
    auto operator| (E1&& e1, E2&& e2) { return any_of(std::forward<E1>(e1), std::forward<E2>(e2)); }

    //---------------------------------------------------------------------------------------------
    // waiter for all events to be triggered in any order
    template<class ...E>
    struct all_of
    {
        all_of(E&& ...e) : _events(std::tuple{ std::tuple<E, bool>{ std::forward<E>(e), false }... }) {}
        void bind_once(auto call_back)
        {
            std::apply([&](auto&& ...ep)
                {
                    (std::get<0>(ep).bind_cancellable(this, [call_back, this, &ep]
                        {
                            std::get<1>(ep) = true;
                            if (all_ready())
                                std::invoke(call_back);
                        }), ...);
                }, _events);
        }

        void bind_cancellable(void* p, auto&& f)
        {
            std::apply([&](auto&& ...ep)
                {
                    (std::get<0>(ep).bind_cancellable(p, f), ...);
                }, _events);
        }

        bool all_ready() const
        {
            return std::apply([](auto&& ...ep)
                {
                    return (std::get<1>(ep) && ...);
                }, _events);
        }

        void cancel_wait(void* p)
        {
            std::apply([=](auto& ...e)
                {
                    (std::get<0>(e).cancel_wait(p), ...);
                }, _events);
        }

    private:
        std::tuple<std::tuple<E, bool>...> _events;
    };

    template<class ...E>
    inline void wait_all(E&& ...e)
    {
        wait(all_of{ decltype(e)(e)... });
    }

    template<class ...E>
    all_of(E&& ...) -> all_of<E...>;

    template<class E1, class E2>
        requires requires { std::declval<E1>().bind_cancellable(0, 0); std::declval<E2>().bind_cancellable(0, 0); }
    auto operator& (E1&& e1, E2&& e2) { return all_of(std::forward<E1>(e1), std::forward<E2>(e2)); }

    //---------------------------------------------------------------------------------------------
    // empty non-signalling event, providing expected interface
    struct empty_event
    {
        void trigger() {}
        void schedule(auto&&...) {}
        void bind(auto&& ...) {}
        void bind_once(auto&& ...) {}
        void bind_cancellable(auto&&...) {}
        void cancel_wait(auto&&...) {}
    };
}
