//-----------------------------------------------------------------------------
//  Copyright (C) 2026, Gene Bushuyev
//
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

// Durable file primitives for crash-safe persistence:
//
//   atomic_replace_file(path, bytes | text | writer)
//       Replaces the whole file so that, after a crash or power loss, path holds either the
//       complete old content or the complete new content, never a partial file and never
//       nothing. The target is never deleted first.
//
//   append_only_file
//       A single-writer append-only file (journal) with flush() for durability and
//       size()/truncate_to() for torn-tail recovery.
//
// Errors are thrown as file_io_error (exception_t<std::error_code>); data() carries the OS
// error: the Win32 error code on Windows (std::system_category), errno elsewhere. The one
// failure of atomic_replace_file that happens after its rename has committed (the flush that
// confirms durability) is thrown as replace_not_durable_error, derived from file_io_error, so
// callers can tell "old content kept" from "new content in place, durability unconfirmed".
//
// What the platform guarantees
// ----------------------------
// Windows (NTFS, ReFS):
//   * FlushFileBuffers writes the file's data and metadata out of the system cache and asks
//     the device to flush its write cache. Nothing in software helps when a drive acknowledges
//     a flush it has not persisted (consumer drives without power-loss protection may do so).
//   * atomic_replace_file writes a temp file in the target's directory, flushes it with
//     FlushFileBuffers, and renames it over the target with MoveFileExW(MOVEFILE_REPLACE_EXISTING
//     | MOVEFILE_WRITE_THROUGH). The temp file is in the same directory, so the move is a rename
//     on one volume, which NTFS logs as a single journaled metadata operation: after a crash the
//     name refers to the old file or to the new file. Microsoft documents MOVEFILE_WRITE_THROUGH
//     as not returning until the move is on disk.
//   * The rename is the commit point. A flush that fails after it (the one after the fallback
//     rename below, or MoveFileExW failing although the temp file is already gone) cannot be
//     undone, so it is reported as replace_not_durable_error, not as an untouched target.
//   * MoveFileExW fails with ERROR_ACCESS_DENIED whenever the target is open, even when every
//     open handle allows FILE_SHARE_DELETE. In that case the rename is redone with
//     SetFileInformationByHandle(FileRenameInfoEx, FILE_RENAME_FLAG_REPLACE_IF_EXISTS |
//     FILE_RENAME_FLAG_POSIX_SEMANTICS) followed by FlushFileBuffers through the same handle
//     (the write-through equivalent). With POSIX semantics the replacement succeeds, existing
//     readers keep reading the old content through their handles, and new opens see the new
//     file. If the target is open by a handle WITHOUT FILE_SHARE_DELETE (std::ifstream, for one),
//     the replacement fails with ERROR_SHARING_VIOLATION, the target is left untouched and the
//     temp file is removed; atomic_replace_options::sharing_retry_timeout can wait for such a
//     handle to close.
//   * There is no directory fsync on Windows and none is needed on NTFS/ReFS: directory entries
//     are journaled metadata, committed by the write-through rename and by FlushFileBuffers.
//   * ReplaceFileW is not used: it is not a single atomic rename (it can fail midway with
//     ERROR_UNABLE_TO_MOVE_REPLACEMENT[_2] and leave the target under another name), it has no
//     write-through option, and it merges the old file's attributes, ACL and streams into the
//     new one. The replacement file therefore gets default attributes and the directory's
//     inherited ACL, not those of the file it replaces.
//   * FAT32/exFAT have no journal, so a rename there is not crash-atomic; network shares give
//     whatever the server gives.
//
// POSIX (fallback, not exercised by Yadro's Windows test runs):
//   * write temp, fsync(temp), rename(temp, target), fsync(directory). On macOS F_FULLFSYNC is
//     used, since fsync there does not flush the drive cache. rename is the commit point; a
//     failed fsync(directory) after it is reported as replace_not_durable_error.
//
// Leftover temp files: a crash between creating and installing the temp file leaves
// "<file name>.<pid>.<n>.tmp" next to the target. It is never mistaken for the target and can
// be removed at startup once no writer is running.

#include "gberror.h"
#include "gbwin.h"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <functional>
#include <memory>
#include <ostream>
#include <span>
#include <streambuf>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <utility>
#include <vector>

#if !defined(GBWINDOWS)
#include <cerrno>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#endif

namespace gb::yadro::util
{
    //-------------------------------------------------------------------------
    // I/O failure; data() is the OS error (Win32 error code on Windows, errno elsewhere)
    using file_io_error = exception_t<std::error_code>;

    // atomic_replace_file got past the point of no return: the rename committed, so the target
    // already holds the new content and the old content is gone, but confirming that the rename
    // reached stable storage failed. After a crash the target may hold either version. Repeating
    // the same atomic_replace_file is safe and, if it succeeds, confirms the new content.
    struct replace_not_durable_error : file_io_error
    {
        using file_io_error::file_io_error;
    };

    namespace detail
    {
#if defined(GBWINDOWS)
        using native_file_handle = HANDLE;
        using unique_file_handle = unique_win_handle;
        using os_error = DWORD;
        inline constexpr const char* os_error_kind = "Win32 error";
#else
        using native_file_handle = int;
        using os_error = int;
        inline constexpr const char* os_error_kind = "errno";

        struct unique_fd
        {
            unique_fd() noexcept = default;
            explicit unique_fd(int fd) noexcept : _fd(fd) {}
            unique_fd(const unique_fd&) = delete;
            auto operator=(const unique_fd&) -> unique_fd& = delete;
            unique_fd(unique_fd&& other) noexcept : _fd(std::exchange(other._fd, -1)) {}

            auto operator=(unique_fd&& other) noexcept -> unique_fd&
            {
                if (this != &other)
                    reset(std::exchange(other._fd, -1));
                return *this;
            }

            ~unique_fd() noexcept { reset(); }

            [[nodiscard]] auto get() const noexcept { return _fd; }
            [[nodiscard]] auto valid() const noexcept { return _fd >= 0; }
            [[nodiscard]] auto release() noexcept { return std::exchange(_fd, -1); }

            void reset(int fd = -1) noexcept
            {
                if (auto old = std::exchange(_fd, fd); old >= 0 && old != fd)
                    ::close(old);
            }

        private:
            int _fd = -1;
        };

        using unique_file_handle = unique_fd;
#endif

        //---------------------------------------------------------------------
        [[nodiscard]] inline std::string path_to_utf8(const std::filesystem::path& file)
        {
            auto text = file.u8string();
            return { reinterpret_cast<const char*>(text.data()), text.size() };
        }

        template<class Error = file_io_error>
        [[noreturn]] GB_YADRO_NOINLINE void throw_file_io_error(os_error code, std::string_view operation,
            const std::filesystem::path& file)
        {
            std::error_code ec{ static_cast<int>(code), std::system_category() };
            throw Error(to_string(operation, " failed for \"", path_to_utf8(file), "\": ",
                ec.message(), " (", os_error_kind, ' ', code, ')'), ec);
        }

        // Test hook: when nonzero, the next post-rename durability confirmation made by
        // atomic_replace_file on this thread reports this error instead of its real result.
        inline thread_local os_error injected_commit_flush_error = 0;

        [[nodiscard]] inline os_error commit_flush_result(os_error actual) noexcept
        {
            if (auto injected = std::exchange(injected_commit_flush_error, os_error{}))
                return injected;
            return actual;
        }

        [[noreturn]] GB_YADRO_NOINLINE inline void throw_file_usage_error(std::string_view message, std::errc code,
            const std::filesystem::path& file)
        {
            throw file_io_error(to_string(message, " (\"", path_to_utf8(file), "\")"), std::make_error_code(code));
        }

        //---------------------------------------------------------------------
        // low-level operations; each returns 0 on success or the OS error code
        inline constexpr std::size_t max_io_chunk = std::size_t{ 1 } << 30;

        // writes every byte, at the current file position when offset is null, else at *offset
        // (advanced by the number of bytes written)
        [[nodiscard]] inline os_error write_all(native_file_handle handle, const std::byte* data, std::size_t size,
            std::uint64_t* offset = nullptr) noexcept
        {
            while (size != 0) {
                auto chunk = std::min(size, max_io_chunk);
#if defined(GBWINDOWS)
                OVERLAPPED overlapped{};
                if (offset) {
                    overlapped.Offset = static_cast<DWORD>(*offset);
                    overlapped.OffsetHigh = static_cast<DWORD>(*offset >> 32);
                }
                DWORD written = 0;
                if (!WriteFile(handle, data, static_cast<DWORD>(chunk), &written, offset ? &overlapped : nullptr))
                    return GetLastError();
                if (written == 0)
                    return ERROR_WRITE_FAULT;
#else
                auto result = offset ? ::pwrite(handle, data, chunk, static_cast<off_t>(*offset)) : ::write(handle, data, chunk);
                if (result < 0) {
                    if (errno == EINTR)
                        continue;
                    return errno;
                }
                if (result == 0)
                    return EIO;
                auto written = static_cast<std::size_t>(result);
#endif
                data += written;
                size -= written;
                if (offset)
                    *offset += written;
            }
            return 0;
        }

        // reads up to size bytes at offset; bytes_read is less than size only at end of file
        [[nodiscard]] inline os_error read_at(native_file_handle handle, std::byte* data, std::size_t size,
            std::uint64_t offset, std::size_t& bytes_read) noexcept
        {
            bytes_read = 0;
            while (bytes_read < size) {
                auto chunk = std::min(size - bytes_read, max_io_chunk);
                auto position = offset + bytes_read;
#if defined(GBWINDOWS)
                OVERLAPPED overlapped{};
                overlapped.Offset = static_cast<DWORD>(position);
                overlapped.OffsetHigh = static_cast<DWORD>(position >> 32);
                DWORD count = 0;
                if (!ReadFile(handle, data + bytes_read, static_cast<DWORD>(chunk), &count, &overlapped)) {
                    auto error = GetLastError();
                    return error == ERROR_HANDLE_EOF ? 0 : error;
                }
#else
                auto result = ::pread(handle, data + bytes_read, chunk, static_cast<off_t>(position));
                if (result < 0) {
                    if (errno == EINTR)
                        continue;
                    return errno;
                }
                auto count = static_cast<std::size_t>(result);
#endif
                if (count == 0)
                    return 0;
                bytes_read += count;
            }
            return 0;
        }

        // flushes data and metadata to stable storage
        [[nodiscard]] inline os_error flush_file(native_file_handle handle) noexcept
        {
#if defined(GBWINDOWS)
            return FlushFileBuffers(handle) ? 0 : GetLastError();
#else
#if defined(__APPLE__)
            if (::fcntl(handle, F_FULLFSYNC) == 0)
                return 0;
            // some file systems do not support F_FULLFSYNC; fall back to fsync
#endif
            while (::fsync(handle) != 0) {
                if (errno != EINTR)
                    return errno;
            }
            return 0;
#endif
        }

        [[nodiscard]] inline os_error file_size(native_file_handle handle, std::uint64_t& size) noexcept
        {
#if defined(GBWINDOWS)
            LARGE_INTEGER value{};
            if (!GetFileSizeEx(handle, &value))
                return GetLastError();
            size = static_cast<std::uint64_t>(value.QuadPart);
#else
            struct stat status {};
            if (::fstat(handle, &status) != 0)
                return errno;
            size = static_cast<std::uint64_t>(status.st_size);
#endif
            return 0;
        }

        [[nodiscard]] inline os_error truncate_file(native_file_handle handle, std::uint64_t size) noexcept
        {
#if defined(GBWINDOWS)
            FILE_END_OF_FILE_INFO info{};
            info.EndOfFile.QuadPart = static_cast<LONGLONG>(size);
            return SetFileInformationByHandle(handle, FileEndOfFileInfo, &info, sizeof(info)) ? 0 : GetLastError();
#else
            while (::ftruncate(handle, static_cast<off_t>(size)) != 0) {
                if (errno != EINTR)
                    return errno;
            }
            return 0;
#endif
        }

#if !defined(GBWINDOWS)
        // makes a rename or a creation in directory durable
        [[nodiscard]] inline os_error sync_directory(const std::filesystem::path& directory) noexcept
        {
            const char* name = directory.empty() ? "." : directory.c_str();
            unique_fd dir{ ::open(name, O_RDONLY | O_DIRECTORY | O_CLOEXEC) };
            if (!dir.valid())
                return errno;
            while (::fsync(dir.get()) != 0) {
                if (errno == EINTR)
                    continue;
                // some file systems cannot fsync a directory; they have nothing to flush
                return errno == EINVAL ? 0 : errno;
            }
            return 0;
        }
#endif

        //---------------------------------------------------------------------
        // stream buffer over a native file handle; it never throws, it records the first OS
        // error and fails every later write
        class file_streambuf final : public std::streambuf
        {
        public:
            explicit file_streambuf(native_file_handle handle)
                : _handle(handle), _buffer(std::make_unique<char[]>(buffer_size))
            {
                setp(_buffer.get(), _buffer.get() + buffer_size);
            }

            [[nodiscard]] os_error error() const noexcept { return _error; }

        protected:
            int_type overflow(int_type ch) override
            {
                if (!drain())
                    return traits_type::eof();
                if (!traits_type::eq_int_type(ch, traits_type::eof())) {
                    *pptr() = traits_type::to_char_type(ch);
                    pbump(1);
                }
                return traits_type::not_eof(ch);
            }

            std::streamsize xsputn(const char* data, std::streamsize size) override
            {
                if (size < buffer_size)
                    return std::streambuf::xsputn(data, size);

                // large writes bypass the buffer
                if (!drain())
                    return 0;
                if (auto error = write_all(_handle, reinterpret_cast<const std::byte*>(data), static_cast<std::size_t>(size))) {
                    _error = error;
                    return 0;
                }
                return size;
            }

            int sync() override { return drain() ? 0 : -1; }

        private:
            bool drain() noexcept
            {
                if (_error)
                    return false;
                if (auto size = static_cast<std::size_t>(pptr() - pbase()); size != 0) {
                    if (auto error = write_all(_handle, reinterpret_cast<const std::byte*>(pbase()), size)) {
                        _error = error;
                        return false;
                    }
                }
                setp(_buffer.get(), _buffer.get() + buffer_size);
                return true;
            }

            static constexpr std::streamsize buffer_size = 64 * 1024;

            native_file_handle _handle;
            std::unique_ptr<char[]> _buffer;
            os_error _error{};
        };

        //---------------------------------------------------------------------
        [[nodiscard]] inline std::filesystem::path temp_sibling_path(const std::filesystem::path& file)
        {
            static std::atomic<std::uint64_t> counter{ 0 };
#if defined(GBWINDOWS)
            auto pid = static_cast<std::uint64_t>(GetCurrentProcessId());
#else
            auto pid = static_cast<std::uint64_t>(::getpid());
#endif
            auto name = file.filename();
            name += to_string('.', pid, '.', counter.fetch_add(1, std::memory_order_relaxed), ".tmp");
            return file.parent_path() / name;
        }

#if defined(GBWINDOWS)
        [[nodiscard]] inline bool is_sharing_error(os_error error) noexcept
        {
            return error == ERROR_SHARING_VIOLATION || error == ERROR_ACCESS_DENIED || error == ERROR_LOCK_VIOLATION;
        }

        // Renames temp over target (same directory) with POSIX semantics, which succeeds while the
        // target is open with FILE_SHARE_DELETE, then flushes the renamed file. Returns the rename's
        // error, 0 once the rename has committed; flush_error then holds the flush's result.
        [[nodiscard]] inline os_error rename_replace_posix_semantics(const std::filesystem::path& temp,
            const std::filesystem::path& target, os_error& flush_error)
        {
            flush_error = 0;
#if defined(FILE_RENAME_FLAG_POSIX_SEMANTICS)
            unique_win_handle file{ CreateFileW(temp.c_str(), GENERIC_WRITE | DELETE, 0, nullptr, OPEN_EXISTING,
                FILE_ATTRIBUTE_NORMAL, nullptr) };
            if (!file.valid())
                return GetLastError();

            // a relative name would be resolved against the current directory, not the temp's
            auto name = std::filesystem::absolute(target).wstring();
            auto name_bytes = name.size() * sizeof(wchar_t);
            std::vector<std::byte> buffer(sizeof(FILE_RENAME_INFO) + name_bytes);
            auto info = reinterpret_cast<FILE_RENAME_INFO*>(buffer.data());
            info->Flags = FILE_RENAME_FLAG_REPLACE_IF_EXISTS | FILE_RENAME_FLAG_POSIX_SEMANTICS;
            info->RootDirectory = nullptr;
            info->FileNameLength = static_cast<DWORD>(name_bytes);
            std::memcpy(info->FileName, name.data(), name_bytes);

            if (!SetFileInformationByHandle(file, FileRenameInfoEx, info, static_cast<DWORD>(buffer.size())))
                return GetLastError();
            // committed: from here on a failure means "replaced, durability unconfirmed"
            flush_error = FlushFileBuffers(file) ? 0 : GetLastError();
            return 0;
#else
            (void)temp;
            (void)target;
            return ERROR_NOT_SUPPORTED;
#endif
        }

        // after a failed MoveFileExW: whether the temp file is certainly gone, i.e. the rename
        // itself happened and only the write-through flush that follows it failed
        [[nodiscard]] inline bool temp_was_renamed(const std::filesystem::path& temp, os_error move_error) noexcept
        {
            // the temp missing *before* the move (deleted by someone else) is not a commit
            if (move_error == ERROR_FILE_NOT_FOUND || move_error == ERROR_PATH_NOT_FOUND)
                return false;
            if (GetFileAttributesW(temp.c_str()) != INVALID_FILE_ATTRIBUTES)
                return false;
            auto error = GetLastError();
            return error == ERROR_FILE_NOT_FOUND || error == ERROR_PATH_NOT_FOUND;
        }
#endif

        //---------------------------------------------------------------------
        // the temp file of one atomic_replace_file call; removed on destruction unless installed
        class temp_replacement
        {
        public:
            temp_replacement(const std::filesystem::path& target, bool remove_on_failure)
                : _remove_on_failure(remove_on_failure)
            {
                if (!target.has_filename())
                    throw_file_usage_error("atomic_replace_file: the target path has no file name", std::errc::invalid_argument, target);

                constexpr int max_attempts = 100;
                for (int attempt = 1; ; ++attempt) {
                    _path = temp_sibling_path(target);
#if defined(GBWINDOWS)
                    _handle = unique_win_handle{ CreateFileW(_path.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_NEW,
                        FILE_ATTRIBUTE_NORMAL, nullptr) };
                    if (_handle.valid())
                        break;
                    auto error = GetLastError();
                    if ((error != ERROR_FILE_EXISTS && error != ERROR_ALREADY_EXISTS) || attempt == max_attempts)
                        throw_file_io_error(error, "atomic_replace_file: CreateFileW", _path);
#else
                    _handle = unique_fd{ ::open(_path.c_str(), O_WRONLY | O_CREAT | O_EXCL | O_CLOEXEC, 0666) };
                    if (_handle.valid())
                        break;
                    auto error = errno;
                    if ((error != EEXIST && error != EINTR) || attempt == max_attempts)
                        throw_file_io_error(error, "atomic_replace_file: open", _path);
#endif
                }
            }

            temp_replacement(const temp_replacement&) = delete;
            auto operator=(const temp_replacement&) -> temp_replacement& = delete;

            ~temp_replacement() noexcept
            {
                _handle.reset();
                if (!_installed && _remove_on_failure) {
#if defined(GBWINDOWS)
                    DeleteFileW(_path.c_str());
#else
                    ::unlink(_path.c_str());
#endif
                }
            }

            [[nodiscard]] auto handle() const noexcept { return _handle.get(); }
            [[nodiscard]] auto&& path() const noexcept { return _path; }

            // Makes the temp file durable and renames it over target. Failures before the rename
            // throw file_io_error with target untouched; a failure to confirm durability after
            // the rename throws replace_not_durable_error.
            void install(const std::filesystem::path& target, std::chrono::milliseconds sharing_retry_timeout)
            {
#if defined(GBWINDOWS)
                if (auto error = flush_file(handle()))
                    throw_file_io_error(error, "atomic_replace_file: FlushFileBuffers", _path);
                if (!CloseHandle(_handle.release()))
                    throw_file_io_error(GetLastError(), "atomic_replace_file: CloseHandle", _path);

                auto deadline = std::chrono::steady_clock::now() + sharing_retry_timeout;
                for (;;) {
                    if (MoveFileExW(_path.c_str(), target.c_str(), MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
                        _installed = true;
                        return;
                    }

                    auto error = GetLastError();
                    if (temp_was_renamed(_path, error)) {
                        _installed = true;
                        throw_file_io_error<replace_not_durable_error>(error,
                            "atomic_replace_file: MoveFileExW write-through after the rename", target);
                    }

                    std::string_view operation = "atomic_replace_file: MoveFileExW";
                    if (error == ERROR_ACCESS_DENIED) {
                        // MoveFileExW will not replace an open target even if it is shared for delete
                        os_error flush_error = 0;
                        auto fallback = rename_replace_posix_semantics(_path, target, flush_error);
                        if (fallback == 0) {
                            _installed = true;
                            if (auto confirm = commit_flush_result(flush_error))
                                throw_file_io_error<replace_not_durable_error>(confirm,
                                    "atomic_replace_file: FlushFileBuffers after the rename", target);
                            return;
                        }
                        // keep the MoveFileExW error when the file system lacks POSIX-semantics renames
                        if (fallback != ERROR_NOT_SUPPORTED && fallback != ERROR_INVALID_PARAMETER && fallback != ERROR_INVALID_FUNCTION) {
                            error = fallback;
                            operation = "atomic_replace_file: SetFileInformationByHandle(FileRenameInfoEx)";
                        }
                    }

                    if (!is_sharing_error(error) || std::chrono::steady_clock::now() >= deadline)
                        throw_file_io_error(error, operation, target);
                    std::this_thread::sleep_for(std::chrono::milliseconds{ 10 });
                }
#else
                (void)sharing_retry_timeout;
                if (auto error = flush_file(handle()))
                    throw_file_io_error(error, "atomic_replace_file: fsync", _path);
                if (::close(_handle.release()) != 0)
                    throw_file_io_error(errno, "atomic_replace_file: close", _path);
                if (::rename(_path.c_str(), target.c_str()) != 0)
                    throw_file_io_error(errno, "atomic_replace_file: rename", target);
                _installed = true;
                if (auto error = commit_flush_result(sync_directory(target.parent_path())))
                    throw_file_io_error<replace_not_durable_error>(error, "atomic_replace_file: fsync(directory) after the rename",
                        target.parent_path());
#endif
            }

        private:
            std::filesystem::path _path;
            unique_file_handle _handle;
            bool _remove_on_failure;
            bool _installed = false;
        };
    }

    //-------------------------------------------------------------------------
    struct atomic_replace_options
    {
        // remove the temp file when writing or installing it fails; false keeps it for inspection
        bool remove_temp_on_failure = true;

        // Windows: how long to keep retrying the install while another handle blocks it (a reader
        // without FILE_SHARE_DELETE, a virus scanner, an indexer); zero fails on the first refusal
        std::chrono::milliseconds sharing_retry_timeout{ 0 };
    };

    //-------------------------------------------------------------------------
    // Replaces file with whatever writer(std::ostream&) writes. The content goes to a temp file in
    // the same directory, which is flushed to stable storage and then renamed over file. The
    // parent directory must exist. Outcomes:
    //   * returns normally: file holds the new content, durably.
    //   * the writer's exception, or file_io_error (other than the next case): nothing was
    //     committed; file is left as it was and the temp file is removed.
    //   * replace_not_durable_error (derived from file_io_error): the rename committed, so file
    //     already holds the new content, but confirming durability failed; see that type.
    //     Catch it before file_io_error when the difference matters.
    template<class Writer>
        requires std::invocable<Writer&, std::ostream&>
    void atomic_replace_file(const std::filesystem::path& file, Writer&& writer, const atomic_replace_options& options = {})
    {
        detail::temp_replacement temp(file, options.remove_temp_on_failure);
        {
            detail::file_streambuf buffer(temp.handle());
            std::ostream out(&buffer);
            std::invoke(writer, out);
            out.flush();
            if (auto error = buffer.error())
                detail::throw_file_io_error(error, "atomic_replace_file: write", temp.path());
            if (!out)
                detail::throw_file_usage_error("atomic_replace_file: the writer left the stream in a failed state",
                    std::errc::io_error, file);
        }
        temp.install(file, options.sharing_retry_timeout);
    }

    inline void atomic_replace_file(const std::filesystem::path& file, std::span<const std::byte> bytes,
        const atomic_replace_options& options = {})
    {
        atomic_replace_file(file, [bytes](std::ostream& out) {
            out.write(reinterpret_cast<const char*>(bytes.data()), static_cast<std::streamsize>(bytes.size()));
        }, options);
    }

    inline void atomic_replace_file(const std::filesystem::path& file, std::string_view text,
        const atomic_replace_options& options = {})
    {
        atomic_replace_file(file, std::as_bytes(std::span{ text }), options);
    }

    //-------------------------------------------------------------------------
    // Single-writer append-only file, e.g. a journal.
    //
    // * Windows opens with GENERIC_READ | GENERIC_WRITE and share mode FILE_SHARE_READ: other
    //   processes may read concurrently (their share mode must include FILE_SHARE_WRITE, as
    //   std::ifstream's does), but no one else may write, delete or rename the file while it is
    //   open. POSIX has no mandatory sharing modes; a second writer is not prevented there.
    // * append() writes at the end of the file as known to this object. If the write fails, the
    //   file is truncated back to the previous size (best effort) and the error is thrown, so a
    //   failed append does not leave bytes that size() does not account for.
    // * Appended bytes are durable only after flush() (FlushFileBuffers / fsync) returns. A crash
    //   before that may keep any prefix of the unflushed bytes: a torn tail.
    // * Recovery: open the file, scan it (read_at), find the end of the last valid record and
    //   call truncate_to(that offset), which also flushes.
    // * A file this object creates is made durable by the first flush() on Windows (NTFS journals
    //   the directory entry); on POSIX the constructor fsyncs the parent directory.
    // * Not thread-safe: synchronize externally if several threads share one object.
    class append_only_file
    {
    public:
        enum class open_mode { open_or_create, open_existing, create_new };

        append_only_file() noexcept = default;

        explicit append_only_file(const std::filesystem::path& file, open_mode mode = open_mode::open_or_create)
            : _path(file)
        {
#if defined(GBWINDOWS)
            auto disposition = mode == open_mode::open_or_create ? OPEN_ALWAYS
                : mode == open_mode::open_existing ? OPEN_EXISTING : CREATE_NEW;
            _handle = unique_win_handle{ CreateFileW(file.c_str(), GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ, nullptr,
                static_cast<DWORD>(disposition), FILE_ATTRIBUTE_NORMAL, nullptr) };
            if (!_handle.valid())
                detail::throw_file_io_error(GetLastError(), "append_only_file: CreateFileW", file);
#else
            auto created = false;
            if (mode != open_mode::open_existing) {
                _handle = detail::unique_fd{ ::open(file.c_str(), O_RDWR | O_CREAT | O_EXCL | O_CLOEXEC, 0666) };
                created = _handle.valid();
                if (!created && (errno != EEXIST || mode == open_mode::create_new))
                    detail::throw_file_io_error(errno, "append_only_file: open", file);
            }
            if (!created) {
                _handle = detail::unique_fd{ ::open(file.c_str(), O_RDWR | O_CLOEXEC) };
                if (!_handle.valid())
                    detail::throw_file_io_error(errno, "append_only_file: open", file);
            }
            else if (auto error = detail::sync_directory(file.parent_path()))
                detail::throw_file_io_error(error, "append_only_file: fsync(directory)", file.parent_path());
#endif
            if (auto error = detail::file_size(_handle.get(), _size))
                detail::throw_file_io_error(error, "append_only_file: file size", file);
        }

        append_only_file(append_only_file&&) noexcept = default;
        auto operator=(append_only_file&&) noexcept -> append_only_file& = default;

        [[nodiscard]] auto is_open() const noexcept { return _handle.valid(); }
        [[nodiscard]] auto&& path() const noexcept { return _path; }

        // bytes in the file: its size when opened plus everything appended, less any truncation
        [[nodiscard]] auto size() const noexcept { return _size; }

        void append(std::span<const std::byte> bytes)
        {
            require_open("append_only_file::append");
            auto offset = _size;
            if (auto error = detail::write_all(_handle.get(), bytes.data(), bytes.size(), &offset)) {
                // do not leave a partial record that size() does not know about
                [[maybe_unused]] auto ignored = detail::truncate_file(_handle.get(), _size);
                detail::throw_file_io_error(error, "append_only_file: write", _path);
            }
            _size = offset;
        }

        void append(std::string_view text) { append(std::as_bytes(std::span{ text })); }

        // makes everything appended so far durable
        void flush()
        {
            require_open("append_only_file::flush");
            if (auto error = detail::flush_file(_handle.get()))
                detail::throw_file_io_error(error, "append_only_file: flush", _path);
        }

        // cuts the file to offset bytes (offset <= size()) and flushes, e.g. to drop a torn tail
        void truncate_to(std::uint64_t offset)
        {
            require_open("append_only_file::truncate_to");
            if (offset > _size)
                detail::throw_file_usage_error("append_only_file: truncate_to offset is past the end of the file",
                    std::errc::invalid_argument, _path);
            if (auto error = detail::truncate_file(_handle.get(), offset))
                detail::throw_file_io_error(error, "append_only_file: truncate", _path);
            _size = offset;
            flush();
        }

        // reads up to buffer.size() bytes starting at offset; returns fewer only at end of file
        [[nodiscard]] std::size_t read_at(std::uint64_t offset, std::span<std::byte> buffer) const
        {
            require_open("append_only_file::read_at");
            std::size_t bytes_read = 0;
            if (auto error = detail::read_at(_handle.get(), buffer.data(), buffer.size(), offset, bytes_read))
                detail::throw_file_io_error(error, "append_only_file: read", _path);
            return bytes_read;
        }

        // closes without flushing
        void close() noexcept
        {
            _handle.reset();
            _size = 0;
        }

    private:
        void require_open(std::string_view operation) const
        {
            if (!is_open())
                detail::throw_file_usage_error(to_string(operation, ": the file is not open"), std::errc::bad_file_descriptor, _path);
        }

        std::filesystem::path _path;
        detail::unique_file_handle _handle;
        std::uint64_t _size = 0;
    };
}
