//-----------------------------------------------------------------------------
//  Copyright (C) 2024, Gene Bushuyev
//
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

// windows utilities

#if defined(_Windows) || defined(__WIN32__) || defined(_WIN32) || defined(_WIN64) || defined(_MSC_VER)
#define GBWINDOWS

#include <functional>
#include <filesystem>
#include "gberror.h"
#include <Windows.h>
#include <Rpcdce.h>
#include <cstdint> 
#include <immintrin.h> // for _mm_pause()

#undef min
#undef max

#pragma comment(lib, "Rpcrt4")

namespace gb::yadro::util
{
    //-------------------------------------------------------------------------
    struct dll
    {
        dll() = default;

        dll(const char* dll_name)
        {
            gbassert(dll_name);
            _handle = LoadLibraryA(dll_name);
        }

        dll(const wchar_t* dll_name)
        {
            gbassert(dll_name);
            _handle = LoadLibraryW(dll_name);
        }

        dll(dll&& other) noexcept : _handle(std::exchange(other._handle, nullptr))
        {
        }

        dll& operator=(dll&& other) noexcept
        {
            if (this != &other)
            {
                reset();
                _handle = std::exchange(other._handle, nullptr);
            }
            return *this;
        }

        dll(const dll&) = delete;
        dll& operator=(const dll&) = delete;

        ~dll() { if (_handle) FreeLibrary(_handle); }

        explicit operator bool() const noexcept { return _handle; }

        void reset() noexcept
        {
            if (_handle)
            {
                FreeLibrary(_handle);
                _handle = nullptr;
            }
        }

        template<class Fn>
        Fn get_function(const char* fun_name) const
        {
            static_assert(std::is_pointer_v<Fn>);
            return _handle ? reinterpret_cast<Fn>(GetProcAddress(_handle, fun_name)) : nullptr;
        }

    private:
        HMODULE _handle{ nullptr };
    };

#if defined(__cplusplus) && (__cplusplus >= 201402L)
    template<class Fn>
    inline auto get_dll_function = [](dll& d, const char* name) { return d.get_function<Fn>(name); };

    template<class Ret, class ...Args>
    inline auto get_dll_function<Ret(Args...)> = [](dll& d, const char* name) { return d.get_function<Ret(*)(Args...)>(name); };
#endif

    //------------------------------------------------------------------------------
    // GUID 34 chars (excluding the hyphens): "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}"
    inline auto get_uuid_wstring(bool use_hyphens = false, bool use_braces = false)
    {
        UUID uuid;

        if (auto status = UuidCreate(&uuid); status == RPC_S_OK)
        {
            wchar_t guid_string[40]{};
            if (auto ret = StringFromGUID2(uuid, guid_string, sizeof(guid_string) / sizeof(guid_string[0])); ret > 0)
            {
                std::wstring result(guid_string);
                if (!use_hyphens)
                    std::erase(result, '-');
                if (!use_braces)
                    return result.substr(1, result.size() - 2);
                return result;
            }
            else
                throw std::runtime_error("StringFromGUID2 failed with error " + std::to_string(ret));
        }
        else
            throw std::runtime_error("UuidCreate failed with error " + std::to_string(status));
    }

    //------------------------------------------------------------------------------
    inline auto get_uuid_string(bool use_hyphens = false, bool use_braces = false)
    {
        auto wuuid = get_uuid_wstring(use_hyphens, use_braces);
        if (auto size_needed = WideCharToMultiByte(CP_UTF8, 0, wuuid.data(), (int)wuuid.size(), nullptr, 0, nullptr, nullptr);
            size_needed > 0)
        {
            std::string result(size_needed, 0);
            WideCharToMultiByte(CP_UTF8, 0, wuuid.data(), (int)wuuid.size(), result.data(), size_needed, nullptr, nullptr);
            return result;
        }
        else
            throw std::runtime_error("WideCharToMultiByte() failed: " + std::to_string(size_needed));
    }

    //------------------------------------------------------------------------------
    // unique file name in Windows temporary directory
    inline auto get_temp_file_path(const std::string& extension = ".tmp")
    {
        return std::filesystem::temp_directory_path() / (get_uuid_string() + extension);
    }


    //------------------------------------------------------------------------------
    // microsleep in 1us increments
    class micro_sleep {
        long long ticks;
        long long freq;
    public:
        explicit micro_sleep(uint64_t microseconds) 
        {
            LARGE_INTEGER f;
            QueryPerformanceFrequency(&f);
            freq = f.QuadPart;

            // Convert microseconds → QPC ticks
            ticks = (freq * microseconds) / 1'000'000ULL;
        }

        void sleep()
        {
            LARGE_INTEGER start, now;
            QueryPerformanceCounter(&start);
            long long target = start.QuadPart + ticks;

            do {
                _mm_pause(); // reduces power + improves loop stability
                QueryPerformanceCounter(&now);
            } while (now.QuadPart < target);
        }
    };
}
#endif
