//-----------------------------------------------------------------------------
//  Copyright (C) 2011-2022, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once
#include <string>
#include <type_traits>
#include <ranges>
#include <bit>
#include <concepts>
#include <cstring>
#include <span>
#include <immintrin.h>

namespace gb::yadro::util
{
    //-------------------------------------------------------------------------
    // hash functions, based on std::hash and boost::hash_combine
    //-------------------------------------------------------------------------
    inline auto make_hash(const char* str) { return std::hash<std::string>{}(str); }
    inline auto make_hash(const wchar_t* str) { return std::hash<std::wstring>{}(str); }
    inline auto make_hash(const auto& v) requires requires{ std::hash<std::remove_cvref_t<decltype(v)>>{}(v); }
    { return std::hash<std::remove_cvref_t<decltype(v)>>{}(v); };
    // TODO: remove after experiment
    inline auto make_hash(unsigned v) { return v; };

    // combine hashes
    inline auto make_hash(const auto& v, const auto&... ts) requires(sizeof ...(ts) != 0);
    // pair, tuple, array
    inline constexpr auto make_hash(auto&& v) requires requires { std::get<0>(v); };
    // ranges
    inline auto make_hash(const std::ranges::common_range auto& r);

    // combine hashes
    inline auto make_hash(const auto& v, const auto&... ts) requires(sizeof ...(ts) != 0)
    {
        auto seed = make_hash(v);
        ((seed ^= make_hash(ts) + 0x9e3779b9 + (seed << 6) + (seed >> 2)), ...);
        return seed;
    }

    // ranges
    inline auto make_hash(const std::ranges::common_range auto& r)
    {
        auto seed = make_hash(0);
        for (auto&& v : r)
            seed = make_hash(seed, v);
        return seed;
    }

    // pair, tuple, array
    inline constexpr auto make_hash(auto&& v) requires requires { std::get<0>(v); }
    {
        return std::apply([](auto&&... t) { return make_hash(t...); }, v);
    }

#if defined(clang_p1061)
    // https://gcc.godbolt.org/z/sMdqMY4Yv
    // https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p1061r5.html
    inline constexpr auto make_hash(auto&& t) requires (std::is_class_v<std::remove_cvref_t<decltype(t)>>)
    {
        auto [...a] = std::forward<decltype(t)>(t);
        return make_hash(a...);
    }
#endif

    using make_hash_t = decltype([](auto&& ...v) { return gb::yadro::util::make_hash(std::forward<decltype(v)>(v)...); });


    //-------------------------------------------------------------------------
    // 128-bit hash type
    //-------------------------------------------------------------------------
    struct hash128_t {
        uint64_t low{};
        uint64_t high{};

        // Knuth reduction algorithm
        uint64_t reduce() const { return low ^ (high * 0x9e3779b97f4a7c15ULL); }

        operator std::pair<uint64_t, uint64_t>() const noexcept {
            return { low, high };
        }

        auto operator<=>(const hash128_t&) const = default;
    };

    //-------------------------------------------------------------------------
    // Concepts
    //-------------------------------------------------------------------------
    template<typename T>
    concept hashable_container = std::ranges::contiguous_range<T>;

    template<typename T>
    concept hashable128 = std::is_trivially_copyable_v<T> || hashable_container<T>;

    //-------------------------------------------------------------------------
    // XXHash128 - Single-pass hashing
    //-------------------------------------------------------------------------
    class xxhash128_scalar {
        // XXH3 prime constants
        static constexpr uint64_t PRIME64_1 = 0x9E3779B185EBCA87ULL;
        static constexpr uint64_t PRIME64_2 = 0xC2B2AE3D27D4EB4FULL;
        static constexpr uint64_t PRIME64_3 = 0x165667B19E3779F9ULL;
        static constexpr uint64_t PRIME64_4 = 0x85EBCA77C2B2AE63ULL;
        static constexpr uint64_t PRIME64_5 = 0x27D4EB2F165667C5ULL;

        static constexpr size_t BLOCK_SIZE = 32;  // Process 32 bytes at a time

        // Initial seed constants for hash combining
        static constexpr uint64_t COMBINE_SEED_LOW = 0x9E3779B97F4A7C15ULL;  // Golden ratio
        static constexpr uint64_t COMBINE_SEED_HIGH = 0xCBF29CE484222325ULL; // FNV offset

    public:
        //---------------------------------------------------------------------
        // Endianness-safe read
        //---------------------------------------------------------------------
        [[nodiscard]] static uint64_t read_u64_le(const uint8_t* p) noexcept {
            uint64_t v;
            std::memcpy(&v, p, sizeof(uint64_t));
            if constexpr (std::endian::native == std::endian::big) {
                return std::byteswap(v);
            }
            return v;
        }

        //---------------------------------------------------------------------
        // Finalization step
        //---------------------------------------------------------------------
        [[nodiscard]] static uint64_t finalize(uint64_t h, uint64_t length) noexcept {
            h ^= length;
            h ^= h >> 33;
            h *= PRIME64_2;
            h ^= h >> 29;
            h *= PRIME64_3;
            h ^= h >> 32;
            return h;
        }

        //---------------------------------------------------------------------
        // Core hashing: Process memory buffer
        //---------------------------------------------------------------------
        [[nodiscard]] static hash128_t hash_mem(const void* ptr, size_t len, uint64_t seed = 0) noexcept {
            const uint8_t* data = static_cast<const uint8_t*>(ptr);

            uint64_t acc1 = seed + PRIME64_1 + PRIME64_2;
            uint64_t acc2 = seed + PRIME64_2;
            uint64_t acc3 = seed;
            uint64_t acc4 = seed - PRIME64_1;

            size_t offset = 0;

            // Process 32-byte blocks (4x 8-byte lanes)
            while (offset + BLOCK_SIZE <= len) {
                uint64_t lane1 = read_u64_le(data + offset);
                uint64_t lane2 = read_u64_le(data + offset + 8);
                uint64_t lane3 = read_u64_le(data + offset + 16);
                uint64_t lane4 = read_u64_le(data + offset + 24);

                // Mix each lane with its accumulator
                acc1 += lane1 * PRIME64_2;
                acc1 = std::rotl(acc1, 31);
                acc1 *= PRIME64_1;

                acc2 += lane2 * PRIME64_2;
                acc2 = std::rotl(acc2, 31);
                acc2 *= PRIME64_1;

                acc3 += lane3 * PRIME64_2;
                acc3 = std::rotl(acc3, 31);
                acc3 *= PRIME64_1;

                acc4 += lane4 * PRIME64_2;
                acc4 = std::rotl(acc4, 31);
                acc4 *= PRIME64_1;

                offset += BLOCK_SIZE;
            }

            // Merge accumulators
            uint64_t merged_low = std::rotl(acc1, 1) + std::rotl(acc2, 7) +
                std::rotl(acc3, 12) + std::rotl(acc4, 18);
            uint64_t merged_high = (acc1 ^ acc3) + (acc2 ^ acc4);

            // Process remaining 8-byte blocks
            while (offset + 8 <= len) {
                uint64_t k = read_u64_le(data + offset);

                merged_low ^= std::rotl(k * PRIME64_2, 31) * PRIME64_1;
                merged_low = std::rotl(merged_low, 27) * PRIME64_1 + PRIME64_4;

                merged_high ^= std::rotl(k * PRIME64_3, 33) * PRIME64_4;
                merged_high = std::rotl(merged_high, 31) * PRIME64_2 + PRIME64_5;

                offset += 8;
            }

            // Process remaining bytes (0-7 bytes)
            while (offset < len) {
                uint64_t byte_val = static_cast<uint64_t>(data[offset]);
                merged_low = std::rotl(merged_low ^ (byte_val * PRIME64_5), 11) * PRIME64_1;
                merged_high = std::rotl(merged_high ^ (byte_val * PRIME64_3), 13) * PRIME64_2;
                ++offset;
            }

            // Final avalanche
            return { finalize(merged_low, len), finalize(merged_high, len) };
        }

        //---------------------------------------------------------------------
        // Hash single value or container
        //---------------------------------------------------------------------
        template<hashable128 T>
        [[nodiscard]] static hash128_t hash_value(const T& value, uint64_t seed = 0) noexcept {
            if constexpr (hashable_container<T>) {
                auto bytes = std::as_bytes(std::span{ value });
                return hash_mem(bytes.data(), bytes.size_bytes(), seed);
            }
            else {
                return hash_mem(&value, sizeof(T), seed);
            }
        }

        //---------------------------------------------------------------------
        // Variadic combiner: Hash multiple arguments
        //---------------------------------------------------------------------
        [[nodiscard]] static hash128_t operator()(const auto& ...args) noexcept
            requires(sizeof...(args) > 0)
        {
            hash128_t result{ COMBINE_SEED_LOW, COMBINE_SEED_HIGH };
            size_t index = 0;

            auto combine = [&](const auto& arg) {
                // Position-dependent seeding for argument order sensitivity
                uint64_t position_seed = result.low ^ (index * PRIME64_5);
                auto h = hash_value(arg, position_seed);

                // Mix hash into result with rotation for better avalanche
                result.low = std::rotl(result.low ^ h.low, 27) * PRIME64_1 + h.high;
                result.high = std::rotl(result.high ^ h.high, 31) * PRIME64_2 + h.low;

                ++index;
                };

            (combine(args), ...);

            // Final mix to ensure all bits influence final result
            result.low = finalize(result.low, sizeof...(args));
            result.high = finalize(result.high, sizeof...(args));

            return result;
        }
    };

    //-------------------------------------------------------------------------
    // XXHash128 Stream - Incremental hashing
    //-------------------------------------------------------------------------
    class xxhash128_stream {
        static constexpr uint64_t PRIME64_1 = 0x9E3779B185EBCA87ULL;
        static constexpr uint64_t PRIME64_2 = 0xC2B2AE3D27D4EB4FULL;
        static constexpr uint64_t PRIME64_3 = 0x165667B19E3779F9ULL;
        static constexpr uint64_t PRIME64_4 = 0x85EBCA77C2B2AE63ULL;
        static constexpr uint64_t PRIME64_5 = 0x27D4EB2F165667C5ULL;

        static constexpr size_t BLOCK_SIZE = 32;
        static constexpr size_t BUFFER_SIZE = BLOCK_SIZE;

        uint64_t acc1;
        uint64_t acc2;
        uint64_t acc3;
        uint64_t acc4;
        uint64_t total_len;
        uint8_t buffer[BUFFER_SIZE];
        size_t buffer_usage;
        uint64_t seed;

    public:
        explicit xxhash128_stream(uint64_t seed_value = 0) noexcept
            : seed(seed_value)
        {
            reset(seed_value);
        }

        //---------------------------------------------------------------------
        // Reset stream to initial state
        //---------------------------------------------------------------------
        void reset(uint64_t seed_value = 0) noexcept {
            seed = seed_value;
            acc1 = seed + PRIME64_1 + PRIME64_2;
            acc2 = seed + PRIME64_2;
            acc3 = seed;
            acc4 = seed - PRIME64_1;
            total_len = 0;
            buffer_usage = 0;
        }

        //---------------------------------------------------------------------
        // Update hash with new data
        //---------------------------------------------------------------------
        void update(const void* input, size_t len) noexcept {
            const uint8_t* data = static_cast<const uint8_t*>(input);
            total_len += len;

            // Fill buffer if there's existing data
            if (buffer_usage > 0) {
                size_t fill = BLOCK_SIZE - buffer_usage;
                if (len < fill) {
                    std::memcpy(buffer + buffer_usage, data, len);
                    buffer_usage += len;
                    return;
                }
                std::memcpy(buffer + buffer_usage, data, fill);
                process_block(buffer);
                data += fill;
                len -= fill;
                buffer_usage = 0;
            }

            // Process full 32-byte blocks directly from input
            while (len >= BLOCK_SIZE) {
                process_block(data);
                data += BLOCK_SIZE;
                len -= BLOCK_SIZE;
            }

            // Store remaining bytes in buffer
            if (len > 0) {
                std::memcpy(buffer, data, len);
                buffer_usage = len;
            }
        }

        //---------------------------------------------------------------------
        // Finalize and get hash value
        //---------------------------------------------------------------------
        [[nodiscard]] hash128_t digest() const noexcept {
            // Merge accumulators
            uint64_t merged_low = std::rotl(acc1, 1) + std::rotl(acc2, 7) +
                std::rotl(acc3, 12) + std::rotl(acc4, 18);
            uint64_t merged_high = (acc1 ^ acc3) + (acc2 ^ acc4);

            // Process buffered data
            size_t offset = 0;

            // Process 8-byte blocks from buffer
            while (offset + 8 <= buffer_usage) {
                uint64_t k = xxhash128_scalar::read_u64_le(buffer + offset);

                merged_low ^= std::rotl(k * PRIME64_2, 31) * PRIME64_1;
                merged_low = std::rotl(merged_low, 27) * PRIME64_1 + PRIME64_4;

                merged_high ^= std::rotl(k * PRIME64_3, 33) * PRIME64_4;
                merged_high = std::rotl(merged_high, 31) * PRIME64_2 + PRIME64_5;

                offset += 8;
            }

            // Process remaining bytes
            while (offset < buffer_usage) {
                uint64_t byte_val = static_cast<uint64_t>(buffer[offset]);
                merged_low = std::rotl(merged_low ^ (byte_val * PRIME64_5), 11) * PRIME64_1;
                merged_high = std::rotl(merged_high ^ (byte_val * PRIME64_3), 13) * PRIME64_2;
                ++offset;
            }

            // Final avalanche
            return {
                xxhash128_scalar::finalize(merged_low, total_len),
                xxhash128_scalar::finalize(merged_high, total_len)
            };
        }

        //---------------------------------------------------------------------
        // Convenience: Update with typed value
        //---------------------------------------------------------------------
        template<hashable128 T>
        void update(const T& value) noexcept {
            if constexpr (hashable_container<T>) {
                auto bytes = std::as_bytes(std::span{ value });
                update(bytes.data(), bytes.size_bytes());
            }
            else {
                update(&value, sizeof(T));
            }
        }

    private:
        //---------------------------------------------------------------------
        // Process one 32-byte block
        //---------------------------------------------------------------------
        void process_block(const uint8_t* block) noexcept {
            uint64_t lane1 = xxhash128_scalar::read_u64_le(block);
            uint64_t lane2 = xxhash128_scalar::read_u64_le(block + 8);
            uint64_t lane3 = xxhash128_scalar::read_u64_le(block + 16);
            uint64_t lane4 = xxhash128_scalar::read_u64_le(block + 24);

            acc1 += lane1 * PRIME64_2;
            acc1 = std::rotl(acc1, 31);
            acc1 *= PRIME64_1;

            acc2 += lane2 * PRIME64_2;
            acc2 = std::rotl(acc2, 31);
            acc2 *= PRIME64_1;

            acc3 += lane3 * PRIME64_2;
            acc3 = std::rotl(acc3, 31);
            acc3 *= PRIME64_1;

            acc4 += lane4 * PRIME64_2;
            acc4 = std::rotl(acc4, 31);
            acc4 *= PRIME64_1;
        }
    };


    //-------------------------------------------------------------------------
    // xxhash128_avx2 - SIMD-accelerated implementation
    // compile with /arch:AVX2 on MSVC or -mavx2 on GCC/Clang
    //-------------------------------------------------------------------------

    // make sure linker fails if AVX2 is defined inconsistently in different translation units
#if defined(__AVX2__)
    inline constexpr int xxhash128_simd_level = 2;
#else
    inline constexpr int xxhash128_simd_level = 0;
#endif

    extern const int xxhash128_simd_guard[xxhash128_simd_level + 1];
    inline const int xxhash128_simd_guard[xxhash128_simd_level + 1] = {};

#if defined(XXHASH128_REQUIRE_AVX2) && !defined(__AVX2__)
#error "XXHASH128: AVX2 required but compiler target does not enable it"
#endif

#ifdef __AVX2__
#if defined(_MSC_VER)
#pragma message("xxhash128_scalar: AVX2 enabled; using AVX2 implementation")
#elif defined(__clang__) || defined(__GNUC__)
#pragma message "xxhash128_scalar: AVX2 enabled; using AVX2 implementation"
#endif

    class xxhash128_avx2
    {
        static constexpr uint64_t PRIME64_1 = 0x9E3779B185EBCA87ULL;
        static constexpr uint64_t PRIME64_2 = 0xC2B2AE3D27D4EB4FULL;
        static constexpr uint64_t PRIME64_3 = 0x165667B19E3779F9ULL;
        static constexpr uint64_t PRIME64_4 = 0x85EBCA77C2B2AE63ULL;
        static constexpr uint64_t PRIME64_5 = 0x27D4EB2F165667C5ULL;

        static constexpr size_t STRIDE = 32;  // Process 32 bytes per SIMD iteration

    public:
        //---------------------------------------------------------------------
        // Runtime CPU feature detection
        //---------------------------------------------------------------------
        [[nodiscard]] static bool is_supported() noexcept {
#ifdef _MSC_VER
            int cpuInfo[4];
            __cpuid(cpuInfo, 0);
            if (cpuInfo[0] >= 7) {
                __cpuidex(cpuInfo, 7, 0);
                return (cpuInfo[1] & (1 << 5)) != 0;  // Check AVX2 bit (EBX bit 5)
            }
            return false;
#elif defined(__GNUC__) || defined(__clang__)
            return __builtin_cpu_supports("avx2");
#else
            return false;
#endif
        }

        //---------------------------------------------------------------------
        // Main hashing function
        //---------------------------------------------------------------------
        [[nodiscard]] static hash128_t hash_mem(const void* ptr, size_t len, uint64_t seed = 0) noexcept {
            const uint8_t* data = static_cast<const uint8_t*>(ptr);
            size_t offset = 0;

            uint64_t merged_low, merged_high;

            if (len >= STRIDE) {
                // Initialize accumulators in AVX2 register
                // Note: _mm256_set_epi64x stores in REVERSE order: (a[3], a[2], a[1], a[0])
                // We want: acc1, acc2, acc3, acc4 to match scalar implementation
                __m256i acc = _mm256_set_epi64x(
                    seed - PRIME64_1,              // acc4 (lane 3)
                    seed,                          // acc3 (lane 2)
                    seed + PRIME64_2,              // acc2 (lane 1)
                    seed + PRIME64_1 + PRIME64_2   // acc1 (lane 0)
                );

                __m256i v_prime1 = _mm256_set1_epi64x(PRIME64_1);
                __m256i v_prime2 = _mm256_set1_epi64x(PRIME64_2);

                // Process 32-byte blocks with SIMD
                while (offset + STRIDE <= len) {
                    __m256i lanes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(data + offset));

                    // acc += lanes * PRIME64_2
                    acc = _mm256_add_epi64(acc, _mm256_mul_gen64(lanes, v_prime2));

                    // acc = rotl(acc, 31)
                    acc = rotl31_avx2(acc);

                    // acc *= PRIME64_1
                    acc = _mm256_mul_gen64(acc, v_prime1);

                    offset += STRIDE;
                }

                // Extract accumulators from SIMD register
                alignas(32) uint64_t a[4];
                _mm256_store_si256(reinterpret_cast<__m256i*>(a), acc);

                // Map back to scalar layout: a[0]=acc1, a[1]=acc2, a[2]=acc3, a[3]=acc4
                uint64_t acc1 = a[0];
                uint64_t acc2 = a[1];
                uint64_t acc3 = a[2];
                uint64_t acc4 = a[3];

                // Merge accumulators (must match scalar implementation)
                merged_low = std::rotl(acc1, 1) + std::rotl(acc2, 7) +
                    std::rotl(acc3, 12) + std::rotl(acc4, 18);
                merged_high = (acc1 ^ acc3) + (acc2 ^ acc4);
            }
            else {
                // Not enough data for SIMD processing; use scalar initialization
                // This matches the scalar version when no blocks are processed
                uint64_t acc1 = seed + PRIME64_1 + PRIME64_2;
                uint64_t acc2 = seed + PRIME64_2;
                uint64_t acc3 = seed;
                uint64_t acc4 = seed - PRIME64_1;

                merged_low = std::rotl(acc1, 1) + std::rotl(acc2, 7) +
                    std::rotl(acc3, 12) + std::rotl(acc4, 18);
                merged_high = (acc1 ^ acc3) + (acc2 ^ acc4);
            }

            // Process remaining bytes (0-31) with scalar code
            return finish_scalar(data, len, offset, merged_low, merged_high);
        }

        //---------------------------------------------------------------------
        // Hash single value or container
        //---------------------------------------------------------------------
        template<hashable128 T>
        [[nodiscard]] static hash128_t hash_value(const T& value, uint64_t seed = 0) noexcept {
            if constexpr (hashable_container<T>) {
                auto bytes = std::as_bytes(std::span{ value });
                return hash_mem(bytes.data(), bytes.size_bytes(), seed);
            }
            else {
                return hash_mem(&value, sizeof(T), seed);
            }
        }

        //---------------------------------------------------------------------
        // Variadic combiner: Hash multiple arguments
        //---------------------------------------------------------------------
        [[nodiscard]] static hash128_t operator()(const auto& ...args) noexcept
            requires(sizeof...(args) > 0)
        {
            return xxhash128_scalar::operator()(args...);
        }

    private:
        //---------------------------------------------------------------------
        // Scalar tail processing for remaining 0-31 bytes
        //---------------------------------------------------------------------
        static hash128_t finish_scalar(const uint8_t* data, size_t len, size_t offset,
            uint64_t ml, uint64_t mh) noexcept {
            // 1. Process remaining 8-byte blocks
            while (offset + 8 <= len) {
                uint64_t k = xxhash128_scalar::read_u64_le(data + offset);

                ml ^= std::rotl(k * PRIME64_2, 31) * PRIME64_1;
                ml = std::rotl(ml, 27) * PRIME64_1 + PRIME64_4;

                mh ^= std::rotl(k * PRIME64_3, 33) * PRIME64_4;
                mh = std::rotl(mh, 31) * PRIME64_2 + PRIME64_5;

                offset += 8;
            }

            // 2. Process remaining bytes (0-7 bytes)
            while (offset < len) {
                uint64_t byte_val = static_cast<uint64_t>(data[offset]);
                ml = std::rotl(ml ^ (byte_val * PRIME64_5), 11) * PRIME64_1;
                mh = std::rotl(mh ^ (byte_val * PRIME64_3), 13) * PRIME64_2;
                ++offset;
            }

            // 3. Final avalanche incorporating total length
            return { xxhash128_scalar::finalize(ml, len), xxhash128_scalar::finalize(mh, len) };
        }

        //---------------------------------------------------------------------
        // AVX2 64-bit multiplication (emulated using 32-bit multiplies)
        //---------------------------------------------------------------------
        static inline __m256i _mm256_mul_gen64(__m256i a, __m256i b) noexcept {
            // 64-bit multiply: (a_hi:a_lo) * (b_hi:b_lo) = a_lo*b_lo + (a_hi*b_lo + a_lo*b_hi) << 32
            // We only need the low 64 bits of the result

            __m256i b_swap = _mm256_shuffle_epi32(b, _MM_SHUFFLE(2, 3, 0, 1));  // swap hi/lo 32-bit parts
            __m256i prod_hi = _mm256_mul_epu32(a, b_swap);  // a_lo * b_hi

            __m256i a_swap = _mm256_shuffle_epi32(a, _MM_SHUFFLE(2, 3, 0, 1));
            __m256i prod_lo = _mm256_mul_epu32(a, b);       // a_lo * b_lo
            __m256i prod_hi2 = _mm256_mul_epu32(a_swap, b); // a_hi * b_lo

            return _mm256_add_epi64(prod_lo,
                _mm256_slli_epi64(_mm256_add_epi64(prod_hi, prod_hi2), 32));
        }

        //---------------------------------------------------------------------
        // AVX2 left rotation by 31 bits
        //---------------------------------------------------------------------
        static inline __m256i rotl31_avx2(__m256i x) noexcept {
            return _mm256_or_si256(_mm256_slli_epi64(x, 31), _mm256_srli_epi64(x, 33));
        }
    };

    using xxhash128 = xxhash128_avx2;
#else
// Fallback when AVX2 is not available
#if defined(_MSC_VER)
#pragma message("AVX2 not enabled, xxhash128_avx2 will fallback to scalar implementation")
#elif defined(__GNUC__) || defined(__clang__)
#pragma message "AVX2 not enabled, xxhash128_avx2 will fallback to scalar implementation"
#endif
    using xxhash128 = xxhash128_scalar;
#endif
}