//-----------------------------------------------------------------------------
//  Copyright (C) 2025, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

#include <vector>
#include <tuple>
#include <complex>
#include <algorithm>
#include <cmath>
#include <numbers>
#include <ranges>
#include <immintrin.h>   // AVX2 / FMA intrinsics
#include "../util/gberror.h"

namespace gb::yadro::algorithm
{
    // simple recursive implementation of the Fast Fourier Transform, in-place, for sequences of size that is a power of 2
    // no scaling is applied to the output (i.e. the DFT is unnormalized, and the inverse DFT must be divided by N).
    // This implementation is not optimized for performance, but serves as a clear and educational example of the FFT algorithm.
    inline void fft_recursive(std::vector<std::complex<double>>& a)
    {
        size_t N = a.size();
        if (N <= 1) return;

        std::vector<std::complex<double>> even(N / 2), odd(N / 2);
        for (size_t i = 0; i < N / 2; ++i)
        {
            even[i] = a[i * 2];
            odd[i] = a[i * 2 + 1];
        }

        fft_recursive(even);
        fft_recursive(odd);

        for (size_t k = 0; k < N / 2; ++k)
        {
            std::complex<double> t = std::polar(1.0, -2 * std::numbers::pi * k / N) * odd[k];
            a[k] = even[k] + t;
            a[k + N / 2] = even[k] - t;
        }
    }

    // AVX2-optimized iterative Cooley-Tukey FFT for sequences of size that is a power of 2, using separate real and imaginary arrays (SoA layout).
#ifdef __AVX2__
#pragma message("FFT: AVX2 enabled; using AVX2 implementation")

    namespace detail {
        // ─────────────────────────────────────────────
        //  Internal helpers
        // ─────────────────────────────────────────────

        /// Bit-reversal permutation in-place (SoA).
        inline void bit_reverse(std::vector<double>& re, std::vector<double>& im)
        {
            const std::size_t N = re.size();
            for (std::size_t i = 1, j = 0; i < N; ++i) {
                std::size_t bit = N >> 1;
                for (; j & bit; bit >>= 1) j ^= bit;
                j ^= bit;
                if (i < j) {
                    std::swap(re[i], re[j]);
                    std::swap(im[i], im[j]);
                }
            }
        }

        /// Scalar Cooley-Tukey butterfly for a single group.
        inline void scalar_stage(std::vector<double>& re, std::vector<double>& im,
            std::size_t base, std::size_t half,
            const std::vector<double>& twRe,
            const std::vector<double>& twIm)
        {
            for (std::size_t k = 0; k < half; ++k) {
                const double tRe = twRe[k] * re[base + k + half] - twIm[k] * im[base + k + half];
                const double tIm = twRe[k] * im[base + k + half] + twIm[k] * re[base + k + half];
                const double uRe = re[base + k];
                const double uIm = im[base + k];
                re[base + k] = uRe + tRe;  im[base + k] = uIm + tIm;
                re[base + k + half] = uRe - tRe;  im[base + k + half] = uIm - tIm;
            }
        }

        /// AVX2 + FMA butterfly for one group, 4 butterflies per iteration.
        /// Requires half >= 4 and twiddle arrays aligned/padded to multiple of 4.
        inline void avx2_stage(std::vector<double>& re, std::vector<double>& im,
            std::size_t base, std::size_t half,
            const std::vector<double>& twRe,
            const std::vector<double>& twIm)
        {
            std::size_t k = 0;
            for (; k + 4 <= half; k += 4) {
                // ── Load twiddle factors W[k..k+3] ──────────────────────────────
                __m256d wRe = _mm256_loadu_pd(&twRe[k]);
                __m256d wIm = _mm256_loadu_pd(&twIm[k]);

                // ── Load "odd" half: b = a[base + k + half] ──────────────────────
                __m256d bRe = _mm256_loadu_pd(&re[base + k + half]);
                __m256d bIm = _mm256_loadu_pd(&im[base + k + half]);

                // ── Complex multiply t = W * b ────────────────────────────────────
                //    tRe = wRe*bRe - wIm*bIm   (FMA: -(wIm*bIm) + wRe*bRe)
                //    tIm = wRe*bIm + wIm*bRe   (FMA:   wIm*bRe  + wRe*bIm)
                __m256d tRe = _mm256_fmsub_pd(wRe, bRe, _mm256_mul_pd(wIm, bIm));
                __m256d tIm = _mm256_fmadd_pd(wIm, bRe, _mm256_mul_pd(wRe, bIm));

                // ── Load "even" half: a = a[base + k] ───────────────────────────
                __m256d aRe = _mm256_loadu_pd(&re[base + k]);
                __m256d aIm = _mm256_loadu_pd(&im[base + k]);

                // ── Butterfly: upper = a + t,  lower = a - t ─────────────────────
                _mm256_storeu_pd(&re[base + k], _mm256_add_pd(aRe, tRe));
                _mm256_storeu_pd(&im[base + k], _mm256_add_pd(aIm, tIm));
                _mm256_storeu_pd(&re[base + k + half], _mm256_sub_pd(aRe, tRe));
                _mm256_storeu_pd(&im[base + k + half], _mm256_sub_pd(aIm, tIm));
            }

            // ── Scalar tail (k..half-1) if half is not a multiple of 4 ──────────
            for (; k < half; ++k) {
                const double tRe = twRe[k] * re[base + k + half] - twIm[k] * im[base + k + half];
                const double tIm = twRe[k] * im[base + k + half] + twIm[k] * re[base + k + half];
                const double uRe = re[base + k];
                const double uIm = im[base + k];
                re[base + k] = uRe + tRe;  im[base + k] = uIm + tIm;
                re[base + k + half] = uRe - tRe;  im[base + k + half] = uIm - tIm;
            }
        }

    } // namespace detail

    /// Core transform.  re/im must have the same power-of-2 size.
    /// sign = -1 → forward FFT,  +1 → inverse FFT (caller must divide by N).
    inline void fft_avx2(std::vector<double>& re, std::vector<double>& im,
        int sign = -1)
    {
        const std::size_t N = re.size();
        util::gbassert(N == im.size());
        util::gbassert(N > 0 && (N & (N - 1)) == 0 && "N must be a power of 2");
        if (N <= 1) return;

        // ── 1. Bit-reversal permutation ──────────────────────────────────────
        detail::bit_reverse(re, im);

        // ── 2. Iterative Cooley-Tukey stages (len = 2, 4, 8, …, N) ──────────
        for (std::size_t len = 2; len <= N; len <<= 1) {
            const std::size_t half = len >> 1;
            const double angle = sign * 2.0 * std::numbers::pi / static_cast<double>(len);

            // Precompute twiddle factors W_len^0 … W_len^{half-1}  (once per stage)
            // Pad to next multiple of 4 so the AVX2 loop never reads past the end.
            const std::size_t pad = (half + 3) & ~std::size_t{ 3 };
            std::vector<double> twRe(pad, 0.0), twIm(pad, 0.0);
            for (std::size_t k = 0; k < half; ++k) {
                twRe[k] = std::cos(angle * static_cast<double>(k));
                twIm[k] = std::sin(angle * static_cast<double>(k));
            }

            // Apply butterflies across every group of size `len`
            for (std::size_t base = 0; base < N; base += len) {
                if (half >= 4)
                    detail::avx2_stage(re, im, base, half, twRe, twIm);
                else
                    detail::scalar_stage(re, im, base, half, twRe, twIm);
            }
        }
    }

    /// Convenience overload: AoS → SoA → transform → AoS.
    /// Matches the interface of the original fft_recursive().
    inline void fft_avx2(std::vector<std::complex<double>>& a, int sign = -1)
    {
        const std::size_t N = a.size();
        std::vector<double> re(N), im(N);
        for (std::size_t i = 0; i < N; ++i) { re[i] = a[i].real(); im[i] = a[i].imag(); }
        fft_avx2(re, im, sign);
        for (std::size_t i = 0; i < N; ++i) a[i] = { re[i], im[i] };
    }

    /// Inverse FFT (normalised).
    inline void ifft_avx2(std::vector<double>& re, std::vector<double>& im)
    {
        fft_avx2(re, im, +1);
        const double inv = 1.0 / static_cast<double>(re.size());
        for (auto& v : re) v *= inv;
        for (auto& v : im) v *= inv;
    }
#else
#pragma message("FFT: AVX2 not enabled; using slow scalar implementation")
#endif

    // Public API: in-place FFT for power-of-2 sizes, dispatching to the appropriate implementation.
    inline void fft(std::vector<std::complex<double>>& a)
    {
#ifdef __AVX2__
        fft_avx2(a);
#else
        fft_recursive(a);
#endif
    }

    // In-place inverse FFT using the conjugation method.
    inline void ifft(std::vector<std::complex<double>>& a)
    {
        for (auto& x : a)
            x = conj(x);

        fft(a);

        for (auto& x : a)
            x = conj(x) / static_cast<double>(a.size());
    }

    // Compute the Discrete Fourier Transform (DFT) of a sequence using the Fast Fourier Transform (FFT) algorithm.
    template <std::ranges::random_access_range Sequence>
    std::vector<std::complex<double>> dft(const Sequence& data)
    {
        static_assert(std::is_convertible_v<std::ranges::range_value_t<Sequence>, double>, "Data must be convertible to double");
        size_t data_size = std::ranges::size(data);
        util::gbassert(data_size != 0, "data must not be empty");
        util::gbassert((data_size & (data_size - 1)) == 0, "Data size must be a power of 2");

        std::vector<std::complex<double>> x(data_size);
        for (size_t i = 0; i < data_size; ++i) {
            x[i] = std::complex<double>(data[i], 0.0);
        }
        fft(x);
        return x;
    }

    // Bluestein's algorithm for arbitrary-length FFT.
    // Computes the unnormalized DFT, then returns all N frequency components as complex numbers.
    // no scaling is applied to the output (i.e. the DFT is unnormalized, and the inverse DFT must be divided by N).
    template <std::ranges::random_access_range Sequence>
    std::vector<std::complex<double>> bluestein_dft(const Sequence& data)
    {
        auto next_power_of_two = [](size_t n) {
            size_t power = 1;
            while (power < n)
                power *= 2;
            return power;
            };
        size_t N = std::ranges::size(data);
        // Choose M as the next power of 2 >= 2*N - 1.
        size_t M = next_power_of_two(2 * N - 1);

        // Allocate and initialize vectors A and B of length M.
        std::vector<std::complex<double>> A(M, 0), B(M, 0);

        // Compute chirp factors.
        // Define:
        //    A[n] = x[n] * exp(-i pi n^2/N)    for n = 0,...,N-1
        //    B[n] = exp(i pi n^2/N)            for n = 0,...,N-1,
        // and set B[M-n] = B[n] for n > 0 (to achieve the proper convolution).
        for (size_t n = 0; n < N; n++) {
            double angle = std::numbers::pi * (static_cast<double>(n * n)) / N;
            A[n] = data[n] * std::exp(std::complex<double>(0, -angle));
            B[n] = std::exp(std::complex<double>(0, angle));
            if (n > 0) {
                B[M - n] = B[n];  // set B[-n] = B[n]
            }
        }

        // Compute FFTs of A and B (length M).
        std::vector<std::complex<double>> A_fft = A;
        std::vector<std::complex<double>> B_fft = B;

        fft(A_fft);
        fft(B_fft);

        // Pointwise multiply: C = A_fft * B_fft.
        std::vector<std::complex<double>> C(M);
        for (size_t i = 0; i < M; i++) {
            C[i] = A_fft[i] * B_fft[i];
        }

        // Compute inverse FFT to get the convolution result.
        ifft(C);
        // NOTE: Do NOT multiply by M here.
        // Our ifft implementation already returns the correct convolution result.

        // Now compute the DFT result:
        //   X[k] = exp(-i pi k^2/N) * C[k]    for k = 0,...,N-1,
        std::vector<std::complex<double>> X(N);
        for (size_t k = 0; k < N; k++) {
            double angle = -std::numbers::pi * (static_cast<double>(k * k)) / N;
            X[k] = C[k] * std::exp(std::complex<double>(0, angle));
        }
        return X;
    }

    /* ======================================================================
       A single resolved frequency component from a DFT output.
       ====================================================================== */
    struct spectral_component
    {
        double magnitude;   // amplitude of this component
        double freq_norm;   // frequency in cycles-per-sample ∈ [0, 0.5]
        // multiply by sample_rate to get physical frequency
        double phase;       // radians ∈ (−π, π], measured at the first sample
    };

    /* ======================================================================
       Configuration for decompose_signal.
       ====================================================================== */
    struct decompose_cfg
    {
        /* Return only k = 0..N/2 (positive frequencies + DC + Nyquist).
           For a real-valued input signal this is the complete non-redundant
           content; bins N/2+1..N-1 are conjugate mirrors.                  */
        bool positive_only = true;

        /* Include k = 0 (DC component, i.e. the signal mean).
           Usually excluded: including it can dominate spectral distance
           comparisons.                                                      */
        bool include_dc = false;

        /* Amplitude normalization.

           Two conventions in common use:

             two_sided = true  (default):
               Divide all bins by N.  Correct for a two-sided spectrum
               where conjugate bins are both present.  A sinusoid of amplitude
               A produces two bins each with magnitude A/2 after this division;
               their sum recovers A.

             two_sided = false:
               Divide all bins except DC and Nyquist by N/2, and DC/Nyquist
               by N.  Correct for a one-sided spectrum: a sinusoid of
               amplitude A produces one bin with magnitude A.

           When normalize = false, raw DFT magnitudes are returned.          */
        bool normalize = true;
        bool two_sided = true;

        /* Sort output by magnitude descending.
           Disabled by default: sorting destroys the frequency-index ordering
           that most processing code (spectral distance, peak detection)
           depends on.  Enable only for human-readable reports.              */
        bool sort = false;
    };

    /* ======================================================================
       Decompose DFT output into (magnitude, frequency, phase) components.

       Input: the complex coefficient vector from any DFT routine
              (bluestein_dft, radix2_fft, etc.).

       Output: one spectral_component per selected bin, in bin-index order
               unless cfg.sort = true.

       freq_norm = k / N ∈ [0, 0.5].  Nyquist is at freq_norm = 0.5
       To convert to physical frequency: freq_hz = freq_norm * sample_rate_hz.
       ====================================================================== */
    inline std::vector<spectral_component>
        decompose_signal(const std::vector<std::complex<double>>& dft, const decompose_cfg& cfg = {})
    {
        const auto N = dft.size();
        if (N == 0) return {};

        /* ---- Frequency index range ------------------------------------ */
        const std::size_t k_start = cfg.include_dc ? 0 : 1;

        /* For even N: positive frequencies are 0..N/2 (Nyquist at N/2).
           For odd  N: positive frequencies are 0..(N-1)/2.
           Integer division N/2 handles both cases correctly.             */
        const std::size_t k_end = cfg.positive_only ? (N / 2) : (N - 1);

        std::vector<spectral_component> out;
        out.reserve(k_end - k_start + 1);

        const double nd = static_cast<double>(N);

        for (std::size_t k = k_start; k <= k_end; ++k)
        {
            const auto c = dft[k];
            auto mag = std::abs(c);

            if (cfg.normalize)
            {
                /* One-sided amplitude correction:
                   All bins except DC (k=0) and Nyquist (k=N/2 for even N)
                   appear as conjugate pairs in the full two-sided spectrum.
                   For a one-sided representation each of those bins should
                   carry the full amplitude of the corresponding sinusoid,
                   so we multiply by 2 (equivalently divide by N/2 rather
                   than N).  DC and Nyquist have no conjugate and divide
                   by N only.                                              */
                if (cfg.two_sided)
                {
                    mag /= nd;
                }
                else
                {
                    const bool is_dc = (k == 0);
                    const bool is_nyquist = (N % 2 == 0) && (k == N / 2);
                    mag /= (is_dc || is_nyquist) ? nd : nd * 0.5;
                }
            }

            /* freq_norm = cycles per sample.
               Nyquist is at k = N/2, freq_norm = 0.5.                   */
            const double freq_norm = static_cast<double>(k) / nd;
            const double phase = std::arg(c);

            out.push_back({ mag, freq_norm, phase });
        }

        if (cfg.sort)
        {
            std::sort(out.begin(), out.end(), [](const spectral_component& a, const spectral_component& b)
                { return a.magnitude > b.magnitude; });
        }

        return out;
    }
}
