//-----------------------------------------------------------------------------
//  Copyright (C) 2011-2025, Gene Bushuyev
//
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#include <cmath>
#include <algorithm>

#include "mackinnon.h"

// NOTE: the former `mackinnon_pvalue` (binary-search response surface) together
// with its helpers `critical_value`, `norm_ppf`, `norm_cdf` and the
// `Coefficients` / `MackinnonConstants` tables were removed — see CODE_REVIEW.md
// finding 3.A. They were dead relative to internal use (adfuller calls
// `mackinnon_pvalue_fast`), only ever referenced the `small` coefficient set,
// and did not implement MacKinnon's actual quantile-dependent surface.

namespace gb::yadro::algorithm {

    // Simplified p-value using piecewise interpolation around the asymptotic
    // critical values with an approximate finite-sample correction.
    double mackinnon_pvalue_fast(double test_stat, int nobs, TrendType trend) {
        // Get asymptotic critical values (from MacKinnon 2010 tables)
        double cv01, cv05, cv10;

        switch (trend) {
        case TrendType::NONE:
            cv01 = -2.58; cv05 = -1.95; cv10 = -1.62;
            break;
        case TrendType::CONSTANT:
            cv01 = -3.43; cv05 = -2.86; cv10 = -2.57;
            break;
        case TrendType::CONSTANT_TREND:
            cv01 = -3.96; cv05 = -3.41; cv10 = -3.12;
            break;
        default:
            cv01 = -3.43; cv05 = -2.86; cv10 = -2.57;
        }

        // Apply finite-sample correction (approximate)
        double T = static_cast<double>(std::max(nobs, 10));
        double correction = (100.0 - T) / (T * 100.0);  // gets smaller as n grows
        cv01 *= (1.0 + correction * 0.5);
        cv05 *= (1.0 + correction * 0.3);
        cv10 *= (1.0 + correction * 0.2);

        if (!std::isfinite(test_stat)) return 1.0;
        if (test_stat < -30.0) return 1e-10;
        if (test_stat > 0.0) return 0.99;

        // Piecewise linear interpolation on log scale
        if (test_stat <= cv01) {
            // Left tail: exponential extrapolation
            double excess = cv01 - test_stat;
            return 0.01 * std::exp(-excess * 0.5);
        }
        else if (test_stat <= cv05) {
            // Between 1% and 5%: log-linear interpolation
            double frac = (test_stat - cv01) / (cv05 - cv01);
            double log_p = std::log(0.01) + frac * (std::log(0.05) - std::log(0.01));
            return std::exp(log_p);
        }
        else if (test_stat <= cv10) {
            // Between 5% and 10%: linear interpolation
            double frac = (test_stat - cv05) / (cv10 - cv05);
            return 0.05 + frac * 0.05;
        }
        else {
            // Right tail: toward 1.0
            double excess = test_stat - cv10;
            return std::clamp(0.10 + excess * 0.15, 0.10, 0.99);
        }
    }
}
