//-----------------------------------------------------------------------------
//  Copyright (C) 2011-2025, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

/*
 * MacKinnon (1994, 2010) p-value approximation with finite-sample correction.
 *
 * Method: Piecewise interpolation around asymptotic critical values with
 * empirical finite-sample adjustments based on sample size.
 *
 * Asymptotic critical values (MacKinnon 2010, Table 1):
 *   No constant:      1%: -2.58,  5%: -1.95,  10%: -1.62
 *   Constant:         1%: -3.43,  5%: -2.86,  10%: -2.57
 *   Constant + Trend: 1%: -3.96,  5%: -3.41,  10%: -3.12
 *
 * Accuracy: Within ±0.02 of statsmodels/R urca for n > 25, typical statistics
 */

namespace gb::yadro::algorithm {

    enum class TrendType { NONE, CONSTANT, CONSTANT_TREND };

    // Main p-value function
    double mackinnon_pvalue(double test_stat, int nunmber_observations, TrendType trend);

    // Simplified alternative using piecewise linear interpolation
    // (faster, slightly less accurate)
    double mackinnon_pvalue_fast(double test_stat, int nunmber_observations, TrendType trend);
}
