//-----------------------------------------------------------------------------
//  Copyright (C) 2025, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once
#include <algorithm>
#include <vector>
#include <cmath>
#include <type_traits>
#include <ranges>
#include <tuple>
#include <numeric>
#include <stdexcept>
#include <concepts>
#include <numbers>
#include <utility>
#include <limits>
#include "../util/gberror.h"
#include "../util/misc.h"

namespace gb::yadro::algorithm
{
    //--------------------------------------------------------------------------------------------
    // 1090-sigmoid function: maps x10 to 0.1 and x90 to 0.9, with a smooth transition in between
    inline double sigmoid1090(double x, double x10, double x90) {
        util::gbassert(!util::almost_equal(x10, x90) && "x10 must not be equal to x90");

        auto x50 = 0.5 * (x10 + x90);
        auto k = 2.0 * std::log(9.0) / (x90 - x10);

        return 1.0 / (1.0 + std::exp(-k * (x - x50)));
    }

    //--------------------------------------------------------------------------------------------
    // Gaussian Filter, smooth curve
    // Constraints:
    // - f(center) = 1.0 exactly
    // - f(left50) = 0.5 exactly
    // - f(right50) = 0.5 exactly
    // - center is the global maximum
    inline double gauss_filter(double x, double left50, double center, double right50) {
        util::gbassert(left50 < center && center < right50 && "Require left50 < center < right50");

        // Solve for sigma: exp(-(x-center)^2 / (2 * sigma^2)) = 0.5
        // -(x-center)^2 / (2 * sigma^2) = ln(0.5)
        // sigma^2 = -(x-center)^2 / (2 * ln(0.5))
        // We can use a pre-calculated divisor: -2 * ln(0.5) = 1.38629436112
        const double log_half_inv = 1.38629436111989;

        double diff = x - center;
        double dist50;

        if (x <= center) {
            dist50 = center - left50;
        }
        else {
            dist50 = right50 - center;
        }

        // f(x) = exp(- (x-center)^2 / (dist50^2 / ln(2)) )
        // This simplifies to:
        double exponent = -(diff * diff) / ((dist50 * dist50) / 0.69314718056);
        return std::exp(exponent);
    }

    /**
     * Double Sigmoid Filter (Stitched)
     * Constraints:
     * - f(center) = 1.0 exactly
     * - f(left50) = 0.5 exactly
     * - f(right50) = 0.5 exactly
     * - center is the global maximum
     * kink at the center for asymmetric curve
     * slower decaying than Gaussian filter
     */
    inline double sigmoid_filter(double x, double left50, double center, double right50) {
        util::gbassert(left50 < center && center < right50 && "Require left50 < center < right50");

        // Logistic function: f(x) = L / (1 + exp(-k(x - x0)))
        // We want f(center) = 1.0. 
        // Since the standard sigmoid 1/(1+exp(0)) is 0.5, we use L = 2.0.

        if (x <= center) {
            // We need 2.0 / (1 + exp(-k * (left50 - center))) = 0.5
            // (1 + exp(-k * (left50 - center))) = 4
            // exp(-k * (left50 - center)) = 3
            // -k * (left50 - center) = ln(3)
            // k = ln(3) / (center - left50)
            const double k = 1.098612288668109691395 / (center - left50); // ln(3)
            return 2.0 / (1.0 + std::exp(-k * (x - center)));
        }
        else {
            // For the right side, k must be positive to ensure it decays as x increases
            // we use the same logic but flip the sign in the exponent.
            const double k = 1.098612288668109691395 / (right50 - center);
            return 2.0 / (1.0 + std::exp(k * (x - center)));
        }
    }

    //--------------------------------------------------------------------------------------------
    // Function to compute mean and standard deviation
    
    enum class VarianceType {
        Population, // Divide by N
        Sample      // Divide by N - 1
    };

    /**
     * Calculates mean and standard deviation using Welford's Algorithm.
     * Returns {NaN, NaN} if the calculation is mathematically undefined for the given input.
     */
    template <std::ranges::input_range R>
        requires std::convertible_to<std::ranges::range_value_t<R>, double>
    auto mean_stddev(const R& data, VarianceType type = VarianceType::Population)
        -> std::pair<double, double>
    {
        double mean = 0.0;
        double m2 = 0.0;
        size_t n = 0;

        for (const auto& value : data) {
            const double x = static_cast<double>(value);
            ++n;
            const double delta = x - mean;
            mean += delta / n;
            const double delta2 = x - mean;
            m2 += delta * delta2;
        }

        // Handle undefined cases
        const double nan = std::numeric_limits<double>::quiet_NaN();

        if (n == 0) {
            return { nan, nan };
        }

        if (type == VarianceType::Sample && n < 2) {
            // Sample variance requires at least two data points
            return { mean, nan };
        }

        const double divisor = (type == VarianceType::Population)
            ? static_cast<double>(n)
            : static_cast<double>(n - 1);

        const double variance = m2 / divisor;
        return { mean, std::sqrt(variance) };
    }

    //--------------------------------------------------------------------------------------------
    // Kolmogorov-Smirnov test function return KS statistic and p-value
    template <std::ranges::random_access_range Sequence1, std::ranges::random_access_range Sequence2>
    std::pair<double, double> kolmogorov_smirnov_test(const Sequence1& sample1, const Sequence2& sample2)
        requires requires(typename Sequence1::value_type t, typename Sequence2::value_type u) { { t <= u } -> std::convertible_to<bool>; }
    {
        auto computeECDF = [](const auto& data) {
            using value_type = typename std::remove_cvref_t<decltype(data)>::value_type;
            std::vector<value_type> sorted_data(data.begin(), data.end());
            std::sort(sorted_data.begin(), sorted_data.end());

            auto n = sorted_data.size();
            std::vector<std::pair<value_type, double>> ecdf(n);
            
            for (size_t index = 0; auto& [value, cdf] : ecdf) {
                value = sorted_data[index];
                cdf = (1. + index) / n;
                ++index;
            }
            
            return ecdf;
        };

        double d_max = 0.0;

        for (auto [i, j, cdf1, cdf2, ecdf1, ecdf2] {std::tuple{size_t(0), size_t(0), 0., 0., computeECDF(sample1), computeECDF(sample2) }};
            i < ecdf1.size() || j < ecdf2.size();)
        {
            if (i < ecdf1.size() && (j == ecdf2.size() || ecdf1[i].first <= ecdf2[j].first)) {
                cdf1 = ecdf1[i].second;
                ++i;
            }
            else {
                cdf2 = ecdf2[j].second;
                ++j;
            }

            d_max = std::max(d_max, std::abs(cdf1 - cdf2));
        }

        // Compute p-value using Kolmogorov-Smirnov distribution
        auto n1 = sample1.size();
        auto n2 = sample2.size();
        auto en_square = static_cast<double>(n1 * n2) / (n1 + n2);
        auto p_value = std::min(1.0, 2.0 * std::exp(-2.0 * en_square * d_max * d_max));

        return { d_max, p_value };
    }

    //--------------------------------------------------------------------------------------------
    namespace detail {
        // Helper function: approximation of the inverse error function (erfinv)
        inline auto erfinv(auto x)
        {
            const auto a = 0.147; // Approximation constant
            auto ln_part = std::log(1 - x * x);
            auto first_part = 2 / (std::numbers::pi * a) + ln_part / 2;
            auto second_part = ln_part / a;

            return std::copysign(std::sqrt(std::sqrt(first_part * first_part - second_part) - first_part), x);
        }

        // Helper function: normal quantile function (percent-point function)
        inline auto normal_quantile(auto p) { return std::sqrt(2) * erfinv(2 * p - 1); }
    }

    //--------------------------------------------------------------------------------------------
    // Shapiro-Wilk test function return W statistic and p-value
    template <std::ranges::sized_range Range>
        requires std::floating_point<std::ranges::range_value_t<Range>>
    auto shapiro_wilk_test(const Range& data) -> std::pair<double, double> 
    {
        auto n = std::ranges::size(data);
        util::gbassert(n >= 3, "Sample size must be at least 3.");

        // Sort data into a vector
        std::vector<double> sorted_data(data.begin(), data.end());
        std::ranges::sort(sorted_data);

        // Compute expected normal order statistics
        std::vector<double> m(n);
        for (std::size_t i = 0; i < n; ++i) {
            double pi = (i + 1.0 - 0.375) / (n + 0.25);
            m[i] = detail::normal_quantile(pi);
        }

        // Compute coefficients (a) using m and normalization
        auto sum_m2 = std::accumulate(m.begin(), m.end(), 0.0, [](auto sum, auto val) {
            return sum + val * val;
            });
        std::vector<double> a(n);
        for (std::size_t i = 0; i < n; ++i) {
            a[i] = m[i] / std::sqrt(sum_m2);
        }

        // Compute mean of data
        auto mean = std::accumulate(sorted_data.begin(), sorted_data.end(), 0.0) / n;

        // Calculate W statistic
        auto numerator = 0.0, denominator = 0.0;
        for (std::size_t i = 0; i < n; ++i) {
            numerator += a[i] * (sorted_data[i] - mean);
            denominator += std::pow(sorted_data[i] - mean, 2);
        }
        numerator = std::pow(numerator, 2);
        auto w = numerator / denominator;

        // Approximate p-value (simple approximation)
        auto p_value = 1.0 - std::exp(-1.2725 * std::pow(w - 1.0, 2));

        return { w, p_value };
    }

}
